### ISSUE TITLE
How to get TextFormField with key GlobalKey

### ISSUE THREAD

**Issue by bartonhammond** [jonsamwell/flutter_gherkin#106]
My form has 
` final _nameFormKey = GlobalKey<FormFieldState>();`
and later
` child: TextFormField(
                  key: _nameFormKey,
                  controller: nameFormFieldController,`

How can I find this element?

**Comment by bartonhammond** [comment]
I added a tooltip:
```
child: Tooltip(
                  message: 'Email',
                  child: TextFormField(
```
then added Step:
```
StepDefinitionGeneric fillFormField() {
  return given2<String, String, FlutterWorld>(
    'I enter {string} into the field with {string} tooltip',
    (value, tooltip, context) async {
      print('fillFormField value: $value tooltip: $tooltip');
      final SerializableFinder locator = find.byTooltip(tooltip);
      await FlutterDriverUtils.enterText(context.world.driver, locator, value);
    },
  );
}
```
And gherkin:
`And I enter "Test Name" into the field with "Email" tooltip`

**Comment by bartonhammond** [comment]
When I try to validate the text w/in the TextFormField that has the GlobalKey I get this:
```
StepDefinitionGeneric thenExpectElementWithTooltipToHaveValue() {
  return given2<String, String, FlutterWorld>(
    RegExp(r'I expect the field with the {string} tooltip to be {string}$'),
    (tooltip, value, context) async {
      try {
        final SerializableFinder locator = find.byTooltip(tooltip);
        final text = await FlutterDriverUtils.getText(
          context.world.driver,
          locator,
        );
        context.expect(text, value);
      } catch (e) {
        await context.reporter.message('Step error: $e', MessageLevel.error);
        rethrow;
      }
    },
  );
}
```
I get this error:
```
Step error: DriverError: Error in Flutter application: Uncaught extension error while executing get_text: Unsupported operation: Type Tooltip is currently not supported by getText
#0      CommandHandlerFactory._getText (package:flutter_driver/src/common/handler_factory.dart:405:7)
<asynchronous suspension>
#1      Future.timeout.<anonymous closure> (dart:async/future_impl.dart)
<asynchronous suspension>
#2      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:378:32)
<asynchronous suspension>
#3      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:580:18)
<asynchronous suspension>
```

**Comment by bartonhammond** [comment]
Credit: https://stackoverflow.com/questions/56079311/flutter-widget-test-find-bykey-does-not-work-if-widget-have-key-globalkeydebu

So I add a Key to the Container:
```
 Container(
                key: Key('homeFormField'),
                width: _formFieldWidth.toDouble(),
                margin: const EdgeInsets.only(right: 10, left: 10),
                child: TextFormField(
                  key: _homeFormKey,
                  controller: homeFormFieldController,
```
Now this gherkin works: `And I fill the "homeFormField" field with "Book Home City, State"`

But I had to add this step definition to test the content
```
StepDefinitionGeneric expectTextFormFieldToHaveValue() {
  return given2<String, String, FlutterWorld>(
    'I expect the {string} textFormField to be {string}',
    (key, value, context) async {
      try {
        final SerializableFinder locator = find.descendant(
            of: find.byValueKey(key), matching: find.byType('TextFormField'));
        final text =
            await FlutterDriverUtils.getText(context.world.driver, locator);
        context.expect(text, value);
      } catch (e) {
        await context.reporter.message('Step error: $e', MessageLevel.error);
        rethrow;
      }
    },
  );
}
```
Now this statement works: `And I expect the "homeFormField" textFormField to be "Book Home City, State"`

**Comment by jonsamwell** [comment]
Yes I usually just use the Key('name') rather than global keys with form fields

```
TextFormField(
    key: const Key('email'),
```

**Comment by bartonhammond** [comment]
But I validate:
```
onChanged: (value) {
                    setState(() {
                      if (_nameFormKey.currentState.validate()) {
                        formReady = _formReady();
                      }
                    });
                  },
```

**Comment by jonsamwell** [comment]
You can just set the form controls `autovalidateMode` to `AutovalidateMode.onUserInteraction`
