### ISSUE TITLE
Is it possible to use flutter_gherkin for testing flutter web?

### ISSUE THREAD

**Issue by zynhrus** [jonsamwell/flutter_gherkin#114]
Hi @jonsamwell thank you so much for create this plugin, It's really helping me a lot to testing the app
But is it possible to test the flutter web with this flutter_gherkin. I have tried to run it but it's failed and always got this error message
`More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.`
I already add '-d <deviceId>' too and still got that error, but when I try to run the test without the flutter_gherkin it runs well.
Do you think that error relates to the flutter_gherkin?

**Comment by jonsamwell** [comment]
Hi @zynhrus 

Once the migration to using the integration_test package and subsequently using `WidgetTester` instead of flutter driver is complete the web will be fully supported.

The migration is pretty much working and I am using it successfully on two huge apps and it is working well, more reliable and quicker.  Feel free to take a look as the code is pretty stable.  I just need to find time to update the documentation around it and I will be updating this library.

Branch: https://github.com/jonsamwell/flutter_gherkin/tree/integration_test__package_support
Issue: https://github.com/jonsamwell/flutter_gherkin/issues/101

**Comment by zynhrus** [comment]
Hi @jonsamwell 

I have tried the branch that you mention above, I can successfully run the automated test with Flutter_gherkin in the Flutter Web. But the problem is I can't generate a report from this test? Am I doing something wrong or is it a bug from this branch?

I try to do this
`JsonReporter(
      path: './integration_response_data.json',
      writeReport: (_, __) => Future<void>.value(),
    ),`
    
Old JsonReporter format
`JsonReporter(
      path: './integration_response_data.json',
    ),`
    
And use the default from your example file
`JsonReporter(
      writeReport: (_, __) => Future<void>.value(),
    ),`
    

<img width="1027" alt="Screen Shot 2021-02-22 at 01 26 43" src="https://user-images.githubusercontent.com/45485381/108634633-06f7cf00-74ad-11eb-9c0d-1d46dd740d05.png">

    
But all of them aren't generate any report. do you have any idea?

**Comment by jonsamwell** [comment]
@zynhrus looks like you are using an old version of the branch try this one

```
  flutter_gherkin:
    git:
      url: https://github.com/jonsamwell/flutter_gherkin.git
      ref: 5f0201101ec44ad5d9d196cff8c23f849f56ea09
```

Note that when the test run fails no report will be generated.  There is an open bug with the Flutter team for this.  We can work around it by writing out own runner but trying to avoid that for now

**Comment by zynhrus** [comment]
Hi @jonsamwell Thanks I already can run and generate the report file, but I still kinda confused with where and how to write the integration test. I already see the example file, but I can't see where is the function of each step.

for example this step: `'When I tap the "add" button'`

But I can't find the function of that steps, something like this 
```
testWidgets('When I tap the "add" button'', (WidgetTester tester) async {
    app.main();
    await tester.pumpAndSettle();

   final addButton = find.byKey("add");

    tester.tap(addButton);
  });
```

Do you have any idea or have any documentation about this?
Thank you

**Comment by jonsamwell** [comment]
Yes there is full documentation in the readme file?  Some step are predefined such as 'When I tap the "xxxx" button' (see https://github.com/jonsamwell/flutter_gherkin/blob/integration_test__package_support/lib/src/flutter/steps/when_tap_widget_step.dart)

**Comment by zynhrus** [comment]
The readme file still uses flutter_driver (https://github.com/jonsamwell/flutter_gherkin/blob/integration_test__package_support/README.md)? 

I can't find the full documentation that uses integration_test, could you share the right readme file URL, please? 

Thank you so much for helping me till now, so sorry if I bother you with many questions :sweat_smile:

And I have one more question.  I already make sure all things are the same as the example file but still got this error when I run the test.

```
Using device Android SDK built for x86.
Starting application: integration_test/app.dart
Installing build/app/outputs/flutter-apk/app.apk...                 3.4s
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        36.9s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 3.2s
I/flutter (12593): Observatory listening on http://127.0.0.1:33959/LJuse8Q3ar4=/
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:59135/LJuse8Q3ar4=/
VMServiceFlutterDriver: Isolate found with number: 3556649698288579
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
I/flutter (12593): 00:00 +0: Login test: Fill email field
VMServiceFlutterDriver: Connected to Flutter application.
I/flutter (12593): Running scenario: Fill email field # :0
I/flutter (12593):    × I fill the "loginForm_emailInput_textField" field with "albert@test.com" # :0 took 33ms  
I/flutter (12593): Exception: Bad state: No element
I/flutter (12593): #0      Iterable.single (dart:core/iterable.dart:558:25)
I/flutter (12593): #1      WidgetController.element (package:flutter_test/src/controller.dart:113:30)
I/flutter (12593): #2      WidgetController.ensureVisible (package:flutter_test/src/controller.dart:961:73)
I/flutter (12593): #3      WidgetTesterAppDriverAdapter.scrollIntoView
(package:flutter_gherkin/src/flutter/adapters/widget_tester_app_driver_adapter.dart:229:21)
I/flutter (12593): #4      WhenFillFieldStep.<anonymous closure>
(package:flutter_gherkin/src/flutter/steps/when_fill_field_step.dart:15:37)
I/flutter (12593): #5      Function._apply (dart:core-patch/function_patch.dart:11:30)
I/flutter (12593): #6      Function.apply (dart:core-patch/function_patch.dart:34:12)
I/flutter (12593): #7      GenericFunctionStepDefinition.onRun
(package:gherkin/src/gherkin/steps/step_definition_implementations.dart:204:21)
I/flutter (12593): #8      StepDefinitionGeneric.run.<anonymous closure>
(package:gherkin/src/gherkin/steps/step_definition.dart:40:32)
I/flutter (12593): #9      Perf.me
I/flutter (12593): (The following exception is now available via WidgetTester.takeException:)
I/flutter (12593): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (12593): The following _Exception was thrown running a test:
I/flutter (12593): Exception: Bad state: No element
I/flutter (12593): 
I/flutter (12593): When the exception was thrown, this was the stack:
I/flutter (12593): #0      GherkinIntegrationTestRunner.runStep
(package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart:274:7)
I/flutter (12593): <asynchronous suspension>
I/flutter (12593): #1      _CustomGherkinIntegrationTestRunner.testFeature0.<anonymous closure>.<anonymous closure>
(file:///Users/Albert/StudioProjects/breaklounge-flutter/integration_test/app_test.dart:23:19)
I/flutter (12593): #2      GherkinIntegrationTestRunner.runScenario.<anonymous closure>
(package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart:164:24)
I/flutter (12593): <asynchronous suspension>
I/flutter (12593): #3      GherkinIntegrationTestRunner.runScenario.<anonymous closure>
(package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart)
I/flutter (12593): #4      testWidgets.<anonymous closure>.<anonymous closure>
(package:flutter_test/src/widget_tester.dart:146:29)
I/flutter (12593): <asynchronous suspension>
I/flutter (12593): #5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
I/flutter (12593): #6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:784:19)
I/flutter (12593): <asynchronous suspension>
I/flutter (12593): #9      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:764:14)
I/flutter (12593): #10     LiveTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1592:12)
I/flutter (12593): #11     IntegrationTestWidgetsFlutterBinding.runTest
(package:integration_test/integration_test.dart:194:17)
I/flutter (12593): #12     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:138:24)
I/flutter (12593): #13     Declarer.test.<anonymous closure>.<anonymous closure>
(package:test_api/src/backend/declarer.dart:175:19)
I/flutter (12593): <asynchronous suspension>
I/flutter (12593): #14     Declarer.test.<anonymous closure>.<anonymous closure>
(package:test_api/src/backend/declarer.dart)
I/flutter (12593): #19     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:173:13)
I/flutter (12593): #20     Invoker.waitForOutstandingCallbacks.<anonymous closure>
(package:test_api/src/backend/invoker.dart:231:15)
I/flutter (12593): #25     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
I/flutter (12593): #26     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>
(package:test_api/src/backend/invoker.dart:383:17)
I/flutter (12593): <asynchronous suspension>
I/flutter (12593): #27     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>
(package:test_api/src/backend/invoker.dart)
I/flutter (12593): #32     Invoker._onRun.<anonymous closure>.<anonymous closure>
(package:test_api/src/backend/invoker.dart:370:9)
I/flutter (12593): #33     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
I/flutter (12593): #34     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
I/flutter (12593): #41     Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
I/flutter (12593): #42     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
I/flutter (12593): (elided 31 frames from dart:async and package:stack_trace)
I/flutter (12593): 
I/flutter (12593): The test description was:
I/flutter (12593):   Fill email field
I/flutter (12593): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (12593): (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the
above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens
first, and then the test will fail due to having not caught or expected the exception.)
I/flutter (12593): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (12593): The following _Exception was thrown running a test:
I/flutter (12593): Exception: Bad state: No element
I/flutter (12593): 
I/flutter (12593): When the exception was thrown, this was the stack:
I/flutter (12593): #0      GherkinIntegrationTestRunner.runStep
(package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart:274:7)
I/flutter (12593): <asynchronous suspension>
I/flutter (12593): #1      _CustomGherkinIntegrationTestRunner.testFeature0.<anonymous closure>.<anonymous closure>
(file:///Users/Albert/StudioProjects/breaklounge-flutter/integration_test/app_test.dart:23:19)
I/flutter (12593): #2      GherkinIntegrationTestRunner.runScenario.<anonymous closure>
(package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart:164:24)
I/flutter (12593): <asynchronous suspension>
I/flutter (12593): #3      GherkinIntegrationTestRunner.runScenario.<anonymous closure>
(package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart)
I/flutter (12593): #4      testWidgets.<anonymous closure>.<anonymous closure>
(package:flutter_test/src/widget_tester.dart:146:29)
I/flutter (12593): <asynchronous suspension>
I/flutter (12593): #5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
I/flutter (12593): #6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:784:19)
I/flutter (12593): <asynchronous suspension>
I/flutter (12593): #9      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:764:14)
I/flutter (12593): #10     LiveTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1592:12)
I/flutter (12593): #11     IntegrationTestWidgetsFlutterBinding.runTest
(package:integration_test/integration_test.dart:194:17)
I/flutter (12593): #12     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:138:24)
I/flutter (12593): #13     Declarer.test.<anonymous closure>.<anonymous closure>
(package:test_api/src/backend/declarer.dart:175:19)
I/flutter (12593): <asynchronous suspension>
I/flutter (12593): #14     Declarer.test.<anonymous closure>.<anonymous closure>
(package:test_api/src/backend/declarer.dart)
I/flutter (12593): #19     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:173:13)
I/flutter (12593): #20     Invoker.waitForOutstandingCallbacks.<anonymous closure>
(package:test_api/src/backend/invoker.dart:231:15)
I/flutter (12593): #25     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
I/flutter (12593): #26     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>
(package:test_api/src/backend/invoker.dart:383:17)
I/flutter (12593): <asynchronous suspension>
I/flutter (12593): #27     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>
(package:test_api/src/backend/invoker.dart)
I/flutter (12593): #32     Invoker._onRun.<anonymous closure>.<anonymous closure>
(package:test_api/src/backend/invoker.dart:370:9)
I/flutter (12593): #33     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
I/flutter (12593): #34     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
I/flutter (12593): #41     Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
I/flutter (12593): #42     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
I/flutter (12593): (elided 31 frames from dart:async and package:stack_trace)
I/flutter (12593): 
I/flutter (12593): The test description was:
I/flutter (12593):   Fill email field
I/flutter (12593): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (12593): 00:01 +0: Login test: Fill email field [E]
I/flutter (12593):   Test failed. See exception logs above.
I/flutter (12593):   The test description was: Fill email field
I/flutter (12593):   
I/flutter (12593): 00:01 +0 -1: (tearDownAll)
Failure Details:
Failure in method: Fill email field
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following _Exception was thrown running a test:
Exception: Bad state: No element

When the exception was thrown, this was the stack:
#0      GherkinIntegrationTestRunner.runStep (package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart:274:7)
<asynchronous suspension>
#1      _CustomGherkinIntegrationTestRunner.testFeature0.<anonymous closure>.<anonymous closure> (file:///Users/Albert/StudioProjects/breaklounge-flutter/integration_test/app_test.dart:23:19)
#2      GherkinIntegrationTestRunner.runScenario.<anonymous closure> (package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart:164:24)
<asynchronous suspension>
#3      GherkinIntegrationTestRunner.runScenario.<anonymous closure> (package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart)
#4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:146:29)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:784:19)
<asynchronous suspension>
#9      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:764:14)
#10     LiveTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1592:12)
#11     IntegrationTestWidgetsFlutterBinding.runTest (package:integration_test/integration_test.dart:194:17)
#12     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:138:24)
#13     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:175:19)
<asynchronous suspension>
#14     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#19     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:173:13)
#20     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:231:15)
#25     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
#26     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:383:17)
<asynchronous suspension>
#27     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
#32     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:370:9)
#33     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
#34     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
#41     Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
#42     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
(elided 31 frames from dart:async and package:stack_trace)

The test description was:
  Fill email field
═════════════════════════════════════════════════════════════════

end of failure 1



I/flutter (12593): 0 scenario ()
I/flutter (12593): 1 step (1 failed)
I/flutter (12593): 0:00:01.269000
Stopping application instance.
I/flutter (12593): 00:01 +1 -1: Some tests failed.
Driver tests failed: 1

```

Do you have any idea?

**Comment by jonsamwell** [comment]
It is now see the new relesase https://pub.dev/packages/flutter_gherkin/versions/3.0.0-rc.1 .  I need to do the documentation but the code is working very well.  Feedback welcome
