### ISSUE TITLE
Support Gherkin Feature/Scenario descriptions

### ISSUE THREAD

**Issue by Moyubori** [jonsamwell/flutter_gherkin#115]
Hi! I've been using this package to run and generate reports for my gherkin tests. I noticed that the description lines are either ignored (feature description) or treated as a syntax error (scenario description) by `flutter_gherkin`. I'm using `JsonReporter` to generate test report json files, that I then convert to HTML reports, but it seems that the `description` fields in `JsonFeature` and `JsonScenario` classes are hardcoded to always be empty strings.

Are there any plans to support handling descriptions? If not, are there any workarounds I could use, to automatically include descriptions in my reports?

**Comment by jonsamwell** [comment]
Yes agree it should support the descriptions, are you able to provide a sample test where the test description raises a syntax error and I will fix that and get the JSON reports working as per spec.

**Comment by Moyubori** [comment]
Thanks for a quick reply. Here's a simple gherkin I used to reproduce the problem:

```
Feature: Example feature
Description goes here.

  Scenario: Example scenario
    Description goes here
    Given something.. 
```

And runner config I use:

```
Future<void> main() async {
  final FlutterTestConfiguration config = FlutterTestConfiguration()
    ..features = [Glob(r"test_driver/bdd/features/example.feature")]
    ..reporters = [
      ProgressReporter(),
      TestRunSummaryReporter(),
      StdoutReporter(),
      JsonReporter(),
    ]
    ..hooks = []
    ..stepDefinitions = []
    ..restartAppBetweenScenarios = false
    ..customStepParameterDefinitions = []
    ..logFlutterProcessOutput = true
    ..exitAfterTestRun = false
    ..targetAppPath = "test_driver/app.dart"
    ..buildFlavor = "tst";
  return await GherkinRunner().execute(config);
}
```

Running that produces following error:
```
Found feature file '.\test_driver\bdd\features\example.feature'
Parsing feature file: '.\test_driver\bdd\features\example.feature'
Error while parsing feature file: '.\test_driver\bdd\features\example.feature'
Exception: Unknown runnable child given to Scenario 'TextLineRunnable'
Unhandled exception:
Exception: Unknown runnable child given to Scenario 'TextLineRunnable'
#0      ScenarioRunnable.addChild (package:gherkin/src/gherkin/runnables/scenario.dart:33:9)
#1      GherkinParser._parseBlock (package:gherkin/src/gherkin/parser.dart:120:21)
#2      GherkinParser._parseBlock (package:gherkin/src/gherkin/parser.dart:109:15)
#3      GherkinParser._parseBlock (package:gherkin/src/gherkin/parser.dart:109:15)
#4      GherkinParser.parseFeatureFile (package:gherkin/src/gherkin/parser.dart:55:7)
<asynchronous suspension>
#5      GherkinRunner.execute (package:gherkin/src/test_runner.dart:47:43)
<asynchronous suspension>
#6      main (file:///<my project path>/test_driver/bdd/bdd_test.dart:34:32)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Process finished with exit code 255
```

When I remove the description under the scenario name, It runs fine.

**Comment by jonsamwell** [comment]
Thanks, I'll take a look at this weekend 👍
