### ISSUE TITLE
The order of features does not work on the Mac os

### ISSUE THREAD

**Issue by Drrrybi** [jonsamwell/flutter_gherkin#116]
In the app_test.dart file, I specified the order ..order = ExecutionOrder.sequential
On computers with windows, everything starts in the correct order.
On computers with Mac OS, the features files run in a strange order, according to my observations, the order by file modification date.
The code was run the same everywhere, from the same branch.
```
import 'dart:async';
import 'package:flutter_gherkin/flutter_gherkin.dart';
import 'package:gherkin/gherkin.dart';
import 'package:glob/glob.dart';

import 'hooks/hook.dart';
import 'steps/step_1_forgot_password.dart';
import 'steps/step_2_sign_up.dart';
import 'steps/step_3_log_in.dart';
import 'steps/step_4_add_set.dart';
import 'steps/step_5_add_card.dart';
import 'steps/step_6_filtering_sorting_cards.dart';
import 'steps/step_7_filtering_sorting_sets.dart';

Future<void> main() async {
  await Future.delayed(const Duration(seconds: 5));
  final FlutterTestConfiguration config = FlutterTestConfiguration()
    ..features = [Glob(r'\features/**.feature')]
    ..targetAppPath = 'test_driver/app.dart'
    ..hooks = [
      Hooks(),
    ]
    ..reporters = <Reporter>[
      ProgressReporter(),
      TestRunSummaryReporter(),
      JsonReporter(path: './report.json')
    ]
    **..order = ExecutionOrder.sequential**
    ..defaultTimeout = const Duration(seconds: 30)
    ..stepDefinitions = <StepDefinitionGeneric<World>>[
      ...forgotPassword,
      ...signUpSteps,
      ...logInSteps,
      ...addSetSteps,
      ...addCardSteps,
      ...filteringSortingCardsSteps,
      ...filteringSortingSetsSteps,
    ]
    ..restartAppBetweenScenarios = false
    ..targetAppWorkingDirectory = '../'
    ..buildFlavor = 'qa'
    ..flutterBuildTimeout = const Duration(minutes: 3)
    ..exitAfterTestRun = true;

  return GherkinRunner().execute(config);
}

```

**Comment by jonsamwell** [comment]
This is order, all it does if you specify the random order is shuffle the array (https://github.com/jonsamwell/dart_gherkin/blob/master/lib/src/test_runner.dart#L71) of tests otherwise it just executed them in the order it finds them on disk.

So I guess the order if finds the feature files based on the globs that you provide is more randomised on a mac https://github.com/jonsamwell/dart_gherkin/blob/master/lib/src/test_runner.dart#L43

Could you enable verbose logging and run this again and paste the output.  This is will tell you the order if finds the feature files.

**Comment by Drrrybi** [comment]
Mac os logs
````
vb@MacBook-Air-Danil test_driver % dart app_test.dart -v
Starting Flutter app under test ‘test_driver/app.dart’, this might take a few moments
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:60862/HyTr5f_N75Q=/
VMServiceFlutterDriver: Isolate found with number: 2714719346598615
VMServiceFlutterDriver: Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver: Connected to Flutter application.
Running scenario: Filtering and sorting sets # ./features/7_filtering_sorting_sets.feature:1
VMServiceFlutterDriver: waitFor message is taking a long time to complete...
   √ Given i have the home screen # ./features/7_filtering_sorting_sets.feature:2 took 1089ms
   × When i tap on the bottom bar sets button # ./features/7_filtering_sorting_sets.feature:3 took 28322ms
Exception: DriverError: Error in Flutter application: Timeout while executing tap: TimeoutException after 0:00:30.000000: Future not completed
#0      VMServiceFlutterDriver.sendCommand (package:flutter_driver/src/driver/vmservice_driver.dart:352:7)
<asynchronous suspension>
#1      FlutterDriver.tap (package:flutter_driver/src/driver/driver.dart:207:11)
#2      FlutterDriverUtils.tap (package:flutter_gherkin/src/flutter/utils/driver_utils.dart:69:18)
#3      SetsScreenTap.executeStep (file:///Users/dvb/Flutter%20Projects/linguamill-cards/test_driver/steps/step_7_filtering_sorting_sets.dart:52:30)
#4      StepDefinition.onRun (package:gherkin/src/gherkin/steps/step_definition_implementations.dart:38:67)
#5      StepDefinitionGeneric.run.<anonymous closure> (package:gherkin/src/gherkin/steps/step_definition.dart:40:32)
#6      Perf.measure (package:gherkin/src/utils/perf.dart:11:26)
#7      StepDefinitionGeneric.run (package:gherkin/src/gherkin/steps/step_definition.dart:35:18)
#8      FeatureFileRunner._runStep.<anonymous closure> (package:gherkin/src/feature_file_runner.dart:319:31)
#9      FeatureFileRunner._runWithinTest (package:gherkin/src/feature_file_runner.dart:348:30)
#10     FeatureFileRunner._runStep (package:gherkin/src/feature_file_runner.dart:317:22)
<asynchronous suspension>
#11     FeatureFileRunner._runScenario (package:gherkin/src/feature_file_runner.dart:247:19)
<asynchronous suspension>
#12     FeatureFileRunner._runScenarioInZone.<anonymous closure> (package:gherkin/src/feature_file_runner.dart:142:30)
#13     _rootRun (dart:async/zone.dart:1190:13)
#14     _CustomZone.run (dart:async/zone.dart:1093:19)
#15     _runZoned (dart:async/zone.dart:1630:10)
#16     runZonedGuarded (dart:async/zone.dart:1618:12)
#17     runZoned (dart:async/zone.dart:1547:12)
#18     FeatureFileRunner._runScenarioInZone (package:gherkin/src/feature_file_runner.dart:140:5)
#19     FeatureFileRunner._runFeature (package:gherkin/src/feature_file_runner.dart:74:21)
<asynchronous suspension>
#20     FeatureFileRunner.run (package:gherkin/src/feature_file_runner.dart:41:38)
#21     GherkinRunner.execute (package:gherkin/src/test_runner.dart:86:45)
<asynchronous suspension>
#22     main (file:///Users/dvb/Flutter%20Projects/linguamill-cards/test_driver/app_test.dart:45:26)
<asynchronous suspension>
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
   - When i have filters and sorting buttons # ./features/7_filtering_sorting_sets.feature:4 took 0ms
   - Then i tap on the sorting_button # ./features/7_filtering_sorting_sets.feature:5 took 0ms
   - And i tap on Alphabetically button # ./features/7_filtering_sorting_sets.feature:6 took 0ms
   - When i tap on the sorting_button # ./features/7_filtering_sorting_sets.feature:7 took 0ms
   - Then i tap on ByDateNO button # ./features/7_filtering_sorting_sets.feature:8 took 0ms
   - When i tap on the sorting_button # ./features/7_filtering_sorting_sets.feature:9 took 0ms
   - Then i tap on byDateON button # ./features/7_filtering_sorting_sets.feature:10 took 0ms
   - When i tap on the filter_button # ./features/7_filtering_sorting_sets.feature:11 took 0ms
   - Then i tap on New button # ./features/7_filtering_sorting_sets.feature:12 took 0ms
   - And i swipe the bottom sheet # ./features/7_filtering_sorting_sets.feature:13 took 0ms
   - When i tap on the filter_button # ./features/7_filtering_sorting_sets.feature:14 took 0ms
   - Then i tap on In progress and New buttons # ./features/7_filtering_sorting_sets.feature:15 took 0ms
   - And i swipe the bottom sheet # ./features/7_filtering_sorting_sets.feature:16 took 0ms
   - When i tap on the filter_button # ./features/7_filtering_sorting_sets.feature:17 took 0ms
   - Then i tap on Memorized and In progress buttons # ./features/7_filtering_sorting_sets.feature:18 took 0ms
   - And i swipe the bottom sheet # ./features/7_filtering_sorting_sets.feature:19 took 0ms
   - When i tap on the filter_button # ./features/7_filtering_sorting_sets.feature:20 took 0ms
   - Then i check mark all the filters # ./features/7_filtering_sorting_sets.feature:21 took 0ms
   - And i swipe the bottom sheet # ./features/7_filtering_sorting_sets.feature:22 took 0ms
   - When i tap on the filter_button # ./features/7_filtering_sorting_sets.feature:23 took 0ms
   - Then i remove all the filters # ./features/7_filtering_sorting_sets.feature:24 took 0ms
   - And i swipe the bottom sheet # ./features/7_filtering_sorting_sets.feature:25 took 0ms
FAILED: Scenario Filtering and sorting sets # ./features/7_filtering_sorting_sets.feature:1
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:60862/HyTr5f_N75Q=/
VMServiceFlutterDriver: Isolate found with number: 2714719346598615
VMServiceFlutterDriver: Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver: Connected to Flutter application.
Running scenario: Reset password # ./features/1_forgot_password.feature:1
VMServiceFlutterDriver: waitFor message is taking a long time to complete...
   √ Given I have welcome_login_button # ./features/1_forgot_password.feature:2 took 1016ms
VMServiceFlutterDriver: tap message is taking a long time to complete...
   × When the user tapped on the welcome_login_button # ./features/1_forgot_password.feature:3 took 30015ms
TimeoutException after 0:00:30.000000: Future not completed
   - Then i tap on the forgot_password_button # ./features/1_forgot_password.feature:4 took 0ms
   - When i have email_field_forgot # ./features/1_forgot_password.feature:5 took 0ms
   - Then i fill the email field # ./features/1_forgot_password.feature:6 took 0ms
   - When i have reset_password_button # ./features/1_forgot_password.feature:7 took 0ms
   - Then i tap on the reset_password_button # ./features/1_forgot_password.feature:8 took 0ms
   - When i have forgot_ok_button # ./features/1_forgot_password.feature:9 took 0ms
   - Then i tap forgot_ok_button # ./features/1_forgot_password.feature:10 took 0ms
   - Given I restart the app # ./features/1_forgot_password.feature:11 took 0ms
FAILED: Scenario Reset password # ./features/1_forgot_password.feature:1
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:60862/HyTr5f_N75Q=/
VMServiceFlutterDriver: Isolate found with number: 2714719346598615
VMServiceFlutterDriver: Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver: Connected to Flutter application.
Running scenario: Add set # ./features/4_add_set.feature:1
VMServiceFlutterDriver: waitFor message is taking a long time to complete...
   √ Given I have bottom_bar_sets_button # ./features/4_add_set.feature:2 took 1031ms
VMServiceFlutterDriver: tap message is taking a long time to complete...
   × When i tap on bottom_bar_sets_button # ./features/4_add_set.feature:3 took 30010ms
TimeoutException after 0:00:30.000000: Future not completed
   - When i have the sets_screen # ./features/4_add_set.feature:4 took 0ms
   - And i have plus_card_set_button # ./features/4_add_set.feature:5 took 0ms
   - Then i tap on plus_card_set_button # ./features/4_add_set.feature:6 took 0ms
   - When i have i have set_title_field # ./features/4_add_set.feature:7 took 0ms
   - Then I fill the set_title_field # ./features/4_add_set.feature:8 took 0ms
   - And i tap on from_language_button # ./features/4_add_set.feature:9 took 0ms
   - And i scroll from language # ./features/4_add_set.feature:10 took 0ms
   - And i choose from language # ./features/4_add_set.feature:11 took 0ms
   - And i tap on to_language_button # ./features/4_add_set.feature:12 took 0ms
   - And i choose to language # ./features/4_add_set.feature:13 took 0ms
   - Then i tap on violet_set_color # ./features/4_add_set.feature:14 took 0ms
   - And i tap on orange_set_color # ./features/4_add_set.feature:15 took 0ms
   - And i tap on pink_set_color # ./features/4_add_set.feature:16 took 0ms
   - And i tap on blue_set_color # ./features/4_add_set.feature:17 took 0ms
   - When i tap on green_set_color # ./features/4_add_set.feature:18 took 0ms
   - Then i tap on create_set_button # ./features/4_add_set.feature:19 took 0ms
   - And i tap on new set # ./features/4_add_set.feature:20 took 0ms
   - And i tap on arrow_back_button # ./features/4_add_set.feature:21 took 0ms
   - When i swpipe the new set # ./features/4_add_set.feature:22 took 0ms
   - Then i tap on edit_icon_button # ./features/4_add_set.feature:23 took 0ms
   - When i update the set_title_field # ./features/4_add_set.feature:24 took 0ms
   - And update tap on from_language_button # ./features/4_add_set.feature:25 took 0ms
   - And update scroll from language # ./features/4_add_set.feature:26 took 0ms
   - And update choose from language # ./features/4_add_set.feature:27 took 0ms
   - And update tap on to_language_button # ./features/4_add_set.feature:28 took 0ms
   - And update choose to language # ./features/4_add_set.feature:29 took 0ms
   - And update tap on pink_set_color # ./features/4_add_set.feature:30 took 0ms
   - Then i tap on Done button # ./features/4_add_set.feature:31 took 0ms
   - And i tap on bottom_bar_home_button # ./features/4_add_set.feature:32 took 0ms
FAILED: Scenario Add set # ./features/4_add_set.feature:1
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:60862/HyTr5f_N75Q=/
VMServiceFlutterDriver: Isolate found with number: 2714719346598615
VMServiceFlutterDriver: Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver: Connected to Flutter application.
Running scenario: Filtering and sorting cards # ./features/6_filtering_sorting_cards.feature:1
VMServiceFlutterDriver: waitFor message is taking a long time to complete...
   √ Given i have the home_screen # ./features/6_filtering_sorting_cards.feature:2 took 1044ms
VMServiceFlutterDriver: waitFor message is taking a long time to complete...
VMServiceFlutterDriver: waitFor message is taking a long time to complete...
   √ When i have filters and sorting buttons # ./features/6_filtering_sorting_cards.feature:3 took 2049ms
```

**Comment by Drrrybi** [comment]
Windows logs


```
PS C:\Users\danil\AndroidStudioProjects\linguamill_cards\test_driver> dart app_test.dart -v
Starting Flutter app under test 'test_driver/app.dart', this might take a few moments
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:54902/4jQoXZ_ZRCw=/
VMServiceFlutterDriver: Isolate found with number: 1652004485531
VMServiceFlutterDriver: Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver: Connected to Flutter application.
Running scenario: Reset password # features\1_forgot_password.feature:1
   √ Given I have welcome_login_button # features\1_forgot_password.feature:2 took 340ms
   √ When the user tapped on the welcome_login_button # features\1_forgot_password.feature:3 took 13915ms
   √ Then i tap on the forgot_password_button # features\1_forgot_password.feature:4 took 87ms
   √ When i have email_field_forgot # features\1_forgot_password.feature:5 took 54ms
   √ Then i fill the email field # features\1_forgot_password.feature:6 took 446ms
   √ When i have reset_password_button # features\1_forgot_password.feature:7 took 46ms
   √ Then i tap on the reset_password_button # features\1_forgot_password.feature:8 took 1145ms
   √ When i have forgot_ok_button # features\1_forgot_password.feature:9 took 46ms
   √ Then i tap forgot_ok_button # features\1_forgot_password.feature:10 took 440ms
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:54902/4jQoXZ_ZRCw=/
VMServiceFlutterDriver: Isolate found with number: 154288912691231
VMServiceFlutterDriver: Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver: Connected to Flutter application.
   √ Given I restart the app # features\1_forgot_password.feature:11 took 4332ms
PASSED: Scenario Reset password # features\1_forgot_password.feature:1
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:54902/4jQoXZ_ZRCw=/
VMServiceFlutterDriver: Isolate found with number: 154288912691231
VMServiceFlutterDriver: Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver: Connected to Flutter application.
Running scenario: Sign up # features\2_sign_up.feature:1
   √ Given I have welcome_signup_button # features\2_sign_up.feature:2 took 470ms
   √ Then the user tapped on the welcome_signup_button # features\2_sign_up.feature:3 took 940ms
   √ When i have signup_email_button # features\2_sign_up.feature:4 took 257ms
   √ Then i tap on signup_email_button # features\2_sign_up.feature:5 took 595ms
   √ Given i have all textfields: name, email, password. # features\2_sign_up.feature:6 took 92ms
   √ When i fill the signup_name_field # features\2_sign_up.feature:7 took 171ms
   √ And i fill the signup_email_field # features\2_sign_up.feature:8 took 366ms
   √ And i fill the signup_password_field # features\2_sign_up.feature:9 took 323ms
   √ Given i have checkbox, Tearms and sign up button # features\2_sign_up.feature:10 took 112ms
   √ When i tap on signup_checkbox # features\2_sign_up.feature:11 took 91ms
   √ And i tap on signup_tearms_link # features\2_sign_up.feature:12 took 423ms
   √ Then i have tearms_conditions and tearms_close_button # features\2_sign_up.feature:13 took 56ms
   √ When i tap on tearms_close_button # features\2_sign_up.feature:14 took 448ms
   √ Then i tap on create_signup_button # features\2_sign_up.feature:15 took 285ms
VMServiceFlutterDriver: waitFor message is taking a long time to complete...
   √ When i have native_lang_signup and for_study_lang_signup # features\2_sign_up.feature:16 took 2093ms
   √ Then i tap on native_lang_signup # features\2_sign_up.feature:17 took 123ms
   √ And i choose native languages # features\2_sign_up.feature:18 took 155ms
   √ And i tap on for_study_lang_signup # features\2_sign_up.feature:19 took 148ms
   √ And i choose language for study # features\2_sign_up.feature:20 took 80ms
   √ When i tap on gender field # features\2_sign_up.feature:21 took 47ms
   √ Then i choose gender # features\2_sign_up.feature:22 took 284ms
   √ And i fill the age # features\2_sign_up.feature:23 took 356ms
   √ And i tap on remember_button # features\2_sign_up.feature:24 took 389ms
   √ When the user tapped on the bottom_bar_profile_button # features\2_sign_up.feature:25 took 1471ms
   √ Then I have the profile_screen # features\2_sign_up.feature:26 took 40ms
   √ When I have the logout_button # features\2_sign_up.feature:27 took 29ms
   √ Then I tap the logout_button # features\2_sign_up.feature:28 took 251ms
   √ And I tap the confirm_yes_button # features\2_sign_up.feature:29 took 449ms
PASSED: Scenario Sign up # features\2_sign_up.feature:1
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:54902/4jQoXZ_ZRCw=/
VMServiceFlutterDriver: Isolate found with number: 154288912691231
VMServiceFlutterDriver: Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver: Connected to Flutter application.
Running scenario: when email and password are in right format and login is clicked # features\3_log_in.feature:1
   √ Given I have welcome_login_button # features\3_log_in.feature:2 took 30ms
   √ Then the user tapped on the welcome_login_button # features\3_log_in.feature:3 took 391ms
VMServiceFlutterDriver: waitFor message is taking a long time to complete...
   √ When I have email_field and password_field # features\3_log_in.feature:4 took 1049ms
   √ Then I fill the email_field # features\3_log_in.feature:5 took 325ms
   √ And I fill the password_field # features\3_log_in.feature:6 took 340ms
   √ And I tap the login_email_button # features\3_log_in.feature:7 took 3564ms
   √ Then I have the home_screen # features\3_log_in.feature:8 took 35ms
PASSED: Scenario when email and password are in right format and login is clicked # features\3_log_in.feature:1
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:54902/4jQoXZ_ZRCw=/
VMServiceFlutterDriver: Isolate found with number: 154288912691231
VMServiceFlutterDriver: Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver: Connected to Flutter application.
Running scenario: Add set # features\4_add_set.feature:1
   √ Given I have bottom_bar_sets_button # features\4_add_set.feature:2 took 33ms
   √ When i tap on bottom_bar_sets_button # features\4_add_set.feature:3 took 390ms
   √ When i have the sets_screen # features\4_add_set.feature:4 took 40ms
   √ And i have plus_card_set_button # features\4_add_set.feature:5 took 43ms
   √ Then i tap on plus_card_set_button # features\4_add_set.feature:6 took 570ms
   √ When i have i have set_title_field # features\4_add_set.feature:7 took 60ms
   √ Then I fill the set_title_field # features\4_add_set.feature:8 took 125ms
   √ And i tap on from_language_button # features\4_add_set.feature:9 took 73ms
   √ And i scroll from language # features\4_add_set.feature:10 took 1213ms
   √ And i choose from language # features\4_add_set.feature:11 took 188ms
   √ And i tap on to_language_button # features\4_add_set.feature:12 took 193ms
   √ And i choose to language # features\4_add_set.feature:13 took 690ms
   √ Then i tap on violet_set_color # features\4_add_set.feature:14 took 94ms
   √ And i tap on orange_set_color # features\4_add_set.feature:15 took 75ms
   √ And i tap on pink_set_color # features\4_add_set.feature:16 took 78ms
   √ And i tap on blue_set_color # features\4_add_set.feature:17 took 75ms
   √ When i tap on green_set_color # features\4_add_set.feature:18 took 73ms
   √ Then i tap on create_set_button # features\4_add_set.feature:19 took 1061ms
   √ And i tap on new set # features\4_add_set.feature:20 took 1525ms
   √ And i tap on arrow_back_button # features\4_add_set.feature:21 took 492ms
   √ When i swpipe the new set # features\4_add_set.feature:22 took 1064ms
   √ Then i tap on edit_icon_button # features\4_add_set.feature:23 took 428ms
   √ When i update the set_title_field # features\4_add_set.feature:24 took 130ms
   √ And update tap on from_language_button # features\4_add_set.feature:25 took 73ms
   √ And update scroll from language # features\4_add_set.feature:26 took 1116ms
   √ And update choose from language # features\4_add_set.feature:27 took 228ms
   √ And update tap on to_language_button # features\4_add_set.feature:28 took 202ms
   √ And update choose to language # features\4_add_set.feature:29 took 767ms
   √ And update tap on pink_set_color # features\4_add_set.feature:30 took 158ms
   √ Then i tap on Done button # features\4_add_set.feature:31 took 911ms
   √ And i tap on bottom_bar_home_button # features\4_add_set.feature:32 took 417ms
PASSED: Scenario Add set # features\4_add_set.feature:1
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:54902/4jQoXZ_ZRCw=/
VMServiceFlutterDriver: Isolate found with number: 154288912691231
VMServiceFlutterDriver: Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver: Connected to Flutter application.
Running scenario: Add card # features\5_add_card.feature:1
   √ Given i have the home_screen # features\5_add_card.feature:2 took 26ms
   √ When i have plus_card_set_button # features\5_add_card.feature:3 took 37ms
   √ Then i tap on plus_card_set_button # features\5_add_card.feature:4 took 459ms
   √ When i have add_word_field and context_field # features\5_add_card.feature:5 took 77ms
   √ Then i fill the add_word_field # features\5_add_card.feature:6 took 116ms
   √ And i tap on add_translation_button # features\5_add_card.feature:7 took 363ms
   √ When i tap on confirm_translation_button # features\5_add_card.feature:8 took 131ms
   √ Then i tap on arrow_back_button # features\5_add_card.feature:9 took 355ms
   √ And i fill the context_field # features\5_add_card.feature:10 took 337ms
   √ When i have create_card_button # features\5_add_card.feature:11 took 65ms
   √ Then i tap on create_card_button # features\5_add_card.feature:12 took 816ms
```

**Comment by Drrrybi** [comment]
I can't figure out why Windows opens everything in order from 1 to 7. 
Mac os opens in its own order. I tried to change the date of saving files, etc. , did not find a solution

**Comment by bartonhammond** [comment]
Any update on this?  I need to run in specific order because of Permissions.

**Comment by Drrrybi** [comment]
@bartonhammond  At the moment, I have not found a solution

**Comment by bartonhammond** [comment]
Couple of ways I thought of. 

I would be happy if I could order the features by the `Feature.name` or the `file` name.

0) Feature name:
change
`for (var entity in glob.listSync()) {`
to 
```
List sorted = glob.listSync().sort((a, b) => a.featureName.compareTo(b.featureName));`
for (var entity in sorted) {
```

1)File name: Takeout the Glob and just pass in an comma separated list of Feature files in the order preferred:
`
..features = 'one.feature, two.feature,three.feature'
for (var feature in features.split(',')) {
`

Something like this would suffice for me anyway...

**Comment by Drrrybi** [comment]
@bartonhammond Thank you

**Comment by jonsamwell** [comment]
@Drrrybi I guess this is just the way the macos accesses files and just doesn't guarantee the order.  With the pending update to use integration_test and `WidgetTester` (see https://github.com/jonsamwell/flutter_gherkin/issues/101#issuecomment-755920726) all tests are pre-generated and will be in order so I don't think there is any point spending time on this ordering issue at the moment.  I would upgrade to us the new way of doing things and this will work as you expect.

**Comment by jonsamwell** [comment]
Actually @bartonhammond @Drrrybi we could add another options to the `ExecutionOrder` enum (https://github.com/jonsamwell/dart_gherkin/blob/master/lib/src/configuration.dart#L15) to have this order by name option

**Comment by bartonhammond** [comment]
If you haven't already done this, I can do a PR.

**Comment by jonsamwell** [comment]
Please do, many thanks

**Comment by jonsamwell** [comment]
The option to sort alphabetically has been added to the latest release so this will ensure the correct order regardless of platform
