### ISSUE TITLE
[3.0.0-rc.1] Exception: Unknown runnable child given to FeatureFile 'TextLineRunnable'

### ISSUE THREAD

**Issue by cpunion** [jonsamwell/flutter_gherkin#131]
Need more details for parsing exception.

```
$ flutter pub run build_runner build --delete-conflicting-outputs --verbose
[ +116 ms] executing: sysctl hw.optional.arm64
[  +24 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[   +8 ms] executing: [/usr/local/Caskroom/flutter/latest/flutter/] git -c log.showSignature=false log
-n 1 --pretty=format:%H
[  +17 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[        ] executing: [/usr/local/Caskroom/flutter/latest/flutter/] git tag --points-at
02c026b03cd31dd3f867e5faeb7e104cce174c5f
[  +32 ms] Exit code 0 from: git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[        ] 2.2.1
[   +7 ms] executing: [/usr/local/Caskroom/flutter/latest/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/usr/local/Caskroom/flutter/latest/flutter/] git ls-remote --get-url origin
[  +13 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +120 ms] executing: [/usr/local/Caskroom/flutter/latest/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +7 ms] executing: sw_vers -productName
[  +21 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +21 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.4
[        ] executing: sw_vers -buildVersion
[  +20 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20F71
[ +101 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +43 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +34 ms] Using /usr/local/Caskroom/flutter/latest/flutter/.pub-cache for the pub cache.
[        ] executing: /usr/local/Caskroom/flutter/latest/flutter/bin/cache/dart-sdk/bin/pub run
build_runner build --delete-conflicting-outputs --verbose
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 563ms

[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 140ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 1.2s

[INFO] Build:Running build...
[INFO] Build:Running build completed, took 27ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 68ms

[SEVERE] flutter_gherkin:gherkin_test_suite on integration_test/gherkin_suite_test.dart (cached):

Exception: Unknown runnable child given to FeatureFile 'TextLineRunnable'
package:gherkin/src/gherkin/runnables/feature_file.dart 41:9                                             FeatureFile.addChild
package:gherkin/src/gherkin/parser.dart 146:21                                                           GherkinParser._parseBlock
package:gherkin/src/gherkin/parser.dart 68:7                                                             GherkinParser.parseFeatureFile
package:gherkin/src/gherkin/ast/feature_file_visitor.dart 13:25                                          FeatureFileVisitor.visit
package:flutter_gherkin/src/flutter/code_generation/generators/gherkin_suite_test_generator.dart 165:5   FeatureFileTestGeneratorVisitor.generateTests
package:flutter_gherkin/src/flutter/code_generation/generators/gherkin_suite_test_generator.dart 110:12  FeatureFileTestGenerator.generate
package:flutter_gherkin/src/flutter/code_generation/generators/gherkin_suite_test_generator.dart 76:20   GherkinSuiteTestGenerator.generateForAnnotatedElement

[SEVERE] Build:
Failed after 135ms
[+4490 ms] "flutter run" took 4,619ms.
[   +8 ms] pub finished with exit code 1
[   +1 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:366:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:241:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +189 ms] ensureAnalyticsSent: 185ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by jonsamwell** [comment]
@cpunion are you able to provide the feature file that is causing this issue?

**Comment by cpunion** [comment]
@jonsamwell Just created a repo to reproduce this problem: https://github.com/cpunion/gherkin_test

**Comment by jonsamwell** [comment]
@cpunion thanks for this.  On first glance I don't think the '*' is supported (in the english version) https://github.com/cpunion/gherkin_test/blob/master/integration_test/features/test.feature#L4

**Comment by cpunion** [comment]
@jonsamwell Thanks, I fixed it, and then it works.

I found a few problems:
1. Every time I changed the feature file, I must change `gherkin_suite_test.dart` too, otherwise it doesn't generate the new `gherkin_suite_test.g.dart` file.
2. It stopped all when a case failed.

**Comment by jonsamwell** [comment]
@cpunion what was the fix for the original issue?

Regarding those points:

1) You can run this command so the pub builder doesn't use the cache when rebuilding

```
flutter pub run build_runner clean
flutter pub run build_runner build --delete-conflicting-outputs
```

2) Stopping the test run when a single test fails is a current limitation with the way the flutter team has implemented the integration_test library.  I agree it is really frustrating!  Acutally it looks like they are push a fix for this soon https://github.com/flutter/flutter/issues/75216

**Comment by cpunion** [comment]
> @cpunion what was the fix for the original issue?

I just replaced '*' with 'Given/And/Then' :-)
> 
> Regarding those points:
> 
> 1. You can run this command so the pub builder doesn't use the cache when rebuilding
> 
> ```
> flutter pub run build_runner clean
> flutter pub run build_runner build --delete-conflicting-outputs
> ```
> 1. Stopping the test run when a single test fails is a current limitation with the way the flutter team has implemented the integration_test library.  I agree it is really frustrating!  Acutally it looks like they are push a fix for this soon [flutter/flutter#75216](https://github.com/flutter/flutter/issues/75216)

Thanks.
