### ISSUE TITLE
Test Execution Internal Late Error after upgrade to 3.0.0.rc.1

### ISSUE THREAD

**Issue by BauerLoser** [jonsamwell/flutter_gherkin#132]
We used the integration test Plugin for Flutter and setup and run succesfully a TestSuite and Steps. After Upgrade to Flutter 2 and the Flutter gherkin 3.0.0.rc.1 our Test Results in the following Error:

```
I/flutter (12545): (The following exception is now available via WidgetTester.takeException:)
I/flutter (12545): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (12545): The following LateError was thrown running a test:
I/flutter (12545): LateInitializationError: Field '_orderedHooks@868221306' has not been initialized.
I/flutter (12545):
I/flutter (12545): When the exception was thrown, this was the stack:
I/flutter (12545): #0      AggregatedHook._orderedHooks (package:gherkin/src/hooks/aggregated_hook.dart)
I/flutter (12545): #1      AggregatedHook._invokeHooks (package:gherkin/src/hooks/aggregated_hook.dart:90:9)
I/flutter (12545): #2      AggregatedHook.onBeforeScenario (package:gherkin/src/hooks/aggregated_hook.dart:47:13)
I/flutter (12545): #3      GherkinIntegrationTestRunner.runScenario.<anonymous closure> (package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart:139:22)
I/flutter (12545): <asynchronous suspension>
I/flutter (12545): <asynchronous suspension>
I/flutter (12545): (elided one frame from package:stack_trace)
I/flutter (12545):
I/flutter (12545): The test description was:
I/flutter (12545):   Test E2E Tests für Meldungserfassung
I/flutter (12545): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (12545): (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends, whichever
happens first, and then the test will fail due to having not caught or expected the exception.)
I/flutter (12545): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (12545): The following LateError was thrown running a test:
I/flutter (12545): LateInitializationError: Field '_orderedHooks@868221306' has not been initialized.
I/flutter (12545):
I/flutter (12545): When the exception was thrown, this was the stack:
I/flutter (12545): #0      AggregatedHook._orderedHooks (package:gherkin/src/hooks/aggregated_hook.dart)
I/flutter (12545): #1      AggregatedHook._invokeHooks (package:gherkin/src/hooks/aggregated_hook.dart:90:9)
I/flutter (12545): #2      AggregatedHook.onBeforeScenario (package:gherkin/src/hooks/aggregated_hook.dart:47:13)
I/flutter (12545): #3      GherkinIntegrationTestRunner.runScenario.<anonymous closure> (package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart:139:22)
I/flutter (12545): <asynchronous suspension>
I/flutter (12545): <asynchronous suspension>
I/flutter (12545): (elided one frame from package:stack_trace)
I/flutter (12545):
I/flutter (12545): The test description was:
I/flutter (12545):   Test E2E Tests für Meldungserfassung
I/flutter (12545): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (12545): 00:01 +0: E2E Tests für Meldungserfassung: Test E2E Tests für Meldungserfassung [E]
I/flutter (12545):   Test failed. See exception logs above.
I/flutter (12545):   The test description was: Test E2E Tests für Meldungserfassung
I/flutter (12545):
I/flutter (12545): 00:01 +0 -1: (tearDownAll)
Failure Details:
Failure in method: Test E2E Tests für Meldungserfassung
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following LateError was thrown running a test:
LateInitializationError: Field '_orderedHooks@868221306' has not
been initialized.

When the exception was thrown, this was the stack:
#0      AggregatedHook._orderedHooks (package:gherkin/src/hooks/aggregated_hook.dart)
#1      AggregatedHook._invokeHooks (package:gherkin/src/hooks/aggregated_hook.dart:90:9)
#2      AggregatedHook.onBeforeScenario (package:gherkin/src/hooks/aggregated_hook.dart:47:13)
#3      GherkinIntegrationTestRunner.runScenario.<anonymous closure> (package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart:139:22)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  Test E2E Tests für Meldungserfassung
═════════════════════════════════════════════════════════════════

end of failure 1



I/flutter (12545): 0 scenario ()
I/flutter (12545): 0 step ()
I/flutter (12545): 0:00:02.032000
```

We had to remove the following import:
`import 'package:flutter_gherkin/flutter_gherkin_integration_test.dart';` because it could not be resolved anymore.
Is there anything else we should have changed? We have no obvious error in the project.

Thanks in advance. We really appreciate the plugin and your work.

**Comment by jonsamwell** [comment]
Sorry for the delay in replying I was on holiday last week.  I'll get this late init error sorted and published.

**Comment by jonsamwell** [comment]
Fixed in https://pub.dev/packages/flutter_gherkin/versions/3.0.0-rc.2
