### ISSUE TITLE
Error: 'Table' isn't a type. data table

### ISSUE THREAD

**Issue by fadhlimaulidri** [jonsamwell/flutter_gherkin#134]
```
  Scenario: Success login

      Given client logged in for APIv4 with "UNAME" and "PWORD"
      When client sends a POST request to 
        | customer_number|123123123.     |
        | product_id.    |2121212        |
```

```
StepDefinitionGeneric ClientSendsPostRequestDatatablePayload() {
  return when1(
    'client sends a POST request to',
    (Table dataTable, context) async {
    },
  );
}
```

when run displayed like below
```
% flutter drive --target=test_driver/app.dart
Running "flutter pub get" in bukalapak_seller_apps...            2,153ms
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        13.2s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                10.3s
test_driver/steps/test_step.dart:153:6: Error: 'Table' isn't a type.
    (Table dataTable, context) async {
     ^^^^^
fadhlimaulidri@Fadhlis-MBP % 
```

**Comment by jonsamwell** [comment]
Table has changed to GherkinTable in the latest releases

**Comment by fadhlimaulidri** [comment]
i am try change like below
```
StepDefinitionGeneric ClientSendsPostRequestDatatablePayload() {
  return when1(
    'client sends a POST request to',
    (Table dataTable, context) async {
    },
  );
}
```
and get error
```
% flutter drive --target=test_driver/app.dart
Running "flutter pub get" in bukalapak_seller_apps...            1,449ms
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        10.4s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 6.0s
tags : @api
Found feature file '/Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/features/example.feature'
Parsing feature file: '/Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/features/example.feature'
Error while parsing feature file: '/Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/features/example.feature'
Exception: Unknown runnable child given to Scenario 'TableRunnable'
Unhandled exception:
Exception: Error when trying to find feature files with patternstest_driver/features/**.feature`ERROR: `Exception: Unknown runnable child given to Scenario 'TableRunnable'`
#0      GherkinRunner._getFeatureFiles (package:gherkin/src/test_runner.dart:130:7)
<asynchronous suspension>
#1      GherkinRunner.execute (package:gherkin/src/test_runner.dart:43:24)
<asynchronous suspension>
```

**Comment by fadhlimaulidri** [comment]
do you mean latest version is 2.0.0 @jonsamwell ?

**Comment by jonsamwell** [comment]
@fadhlimaulidri it looks like your feature file `/Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/features/example.feature`

is not well formed could you paste the contents here so I can see what is wrong.

Yes in v2 Table changed to GherkinTable

**Comment by fadhlimaulidri** [comment]
i have try again. this is my gherkin code
```
Feature: Seller apps onboarding

      @api
      Scenario: Success login
		
        Given client logged in for APIv4 with "UNAME" and "PWORD"
	When client sends a POST request to
	  |customer_number | 01428800700 |
	  |product_id      | 2           |
```

finally that work, i dont have idea why error before. thanks you @jonsamwell . but i have get issue after that, maybe i create at new issue

**Comment by jonsamwell** [comment]
Yes create a new issue it you think something is not working
