### ISSUE TITLE
Handle alert notification confirmation

### ISSUE THREAD

**Issue by fadhlimaulidri** [jonsamwell/flutter_gherkin#147]
how to handle alert confirmation?

```
fadhlimaulidri@Fadhlis-MBP bukalapak_seller_apps % flutter drive --target=test_driver/app.dart
Running "flutter pub get" in bukalapak_seller_apps...            1,502ms
Running pod install...                                              8.5s
Running Xcode build...
 └─Compiling, linking and signing...                        16.6s
Xcode build done.                                           47.5s
8.3.0 - [Firebase/Messaging][I-FCM012002] Error in
application:didFailToRegisterForRemoteNotificationsWithError: remote notifications are not supported
in the simulator
8.3.0 - [Firebase/Messaging][I-FCM002022] APNS device token not set before retrieving FCM Token for
Sender ID '1070156546349'. Notifications to this FCM Token will not be delivered over APNS.Be sure to
re-retrieve the FCM token once the APNS device token is set.
tags : @android
Found feature file '/Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/features/1_SEL-263,SEL-146 (1).feature'
Parsing feature file: '/Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/features/1_SEL-263,SEL-146 (1).feature'
Found 1 feature file(s) to run
Executing features in random order
Starting Flutter app under test 'test_driver/app.dart', this might take a few moments
8.3.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
flutter: Observatory listening on http://127.0.0.1:54634/uONq5a7NWA4=/
8.3.0 - [Firebase/Messaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will
swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase
Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the
instructions at:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
8.3.0 - [Firebase/Messaging][I-FCM012002] Error in
application:didFailToRegisterForRemoteNotificationsWithError: remote notifications are not supported
in the simulator
Attempting to running feature 'Seller apps onboarding' # /Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/features/1_SEL-263,SEL-146 (1).feature:1
Ignoring scenario 'API test' as tag expression '@android' not satisfied # /Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/features/1_SEL-263,SEL-146 (1).feature:1
Ignoring scenario 'Success login' as tag expression '@android' not satisfied # /Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/features/1_SEL-263,SEL-146 (1).feature:1
Creating new world for scenario '[Test] Seller App Onboarding Page - Login Page' # /Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/features/1_SEL-263,SEL-146 (1).feature:18
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:54638/LOXC8PhgFJ0=/
VMServiceFlutterDriver: Isolate found with number: 3974157986843511
VMServiceFlutterDriver: Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver: Connected to Flutter application.
Running scenario: [Test] Seller App Onboarding Page - Login Page # /Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/features/1_SEL-263,SEL-146 (1).feature:18
Attempting to run step 'Given there is seller who have been registered before' # /Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/features/1_SEL-263,SEL-146 (1).feature:23
username: fadhlitest1
password: password123
email: fadhlimaulidriutest1@gmail.com
phone_number: 081233445566
   √ Given there is seller who have been registered before # /Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/features/1_SEL-263,SEL-146 (1).feature:23 took 6ms
Attempting to run step 'And User start selling' # /Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/features/1_SEL-263,SEL-146 (1).feature:24
[VERBOSE-2:rasterizer.cc(642)] Last layer tree was null when screenshotting.
   × And User start selling # /Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/features/1_SEL-263,SEL-146 (1).feature:24 took 37ms
Exception: DriverError: Error in Flutter application: Uncaught extension error while executing tap: 'package:flutter_driver/src/extension/extension.dart': Failed assertion: line 372 pos 14: 'WidgetsBinding.instance!.isRootWidgetAttached || !command.requiresRootWidgetAttached': No root widget is attached; have you remembered to call runApp()?
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:372:14)
#3      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:597:32)
<asynchronous suspension>


#0      VMServiceFlutterDriver.sendCommand (package:flutter_driver/src/driver/vmservice_driver.dart:320:7)
<asynchronous suspension>
#1      FlutterDriver.tap (package:flutter_driver/src/driver/driver.dart:202:5)
<asynchronous suspension>
#2      FlutterDriverUtils.tap (package:flutter_gherkin/src/flutter/utils/driver_utils.dart:69:5)
<asynchronous suspension>
#3      userStartSelling.<anonymous closure> (file:///Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/steps/test_step.dart:46:7)
<asynchronous suspension>
#4      Future.timeout.<anonymous closure> (dart:async/future_impl.dart)
<asynchronous suspension>
#5      StepDefinitionGeneric.run.<anonymous closure> (package:gherkin/src/gherkin/steps/step_definition.dart:42:26)
<asynchronous suspension>
#6      Perf.measure (package:gherkin/src/utils/perf.dart:11:14)
<asynchronous suspension>
#7      StepDefinitionGeneric.run (package:gherkin/src/gherkin/steps/step_definition.dart:37:7)
<asynchronous suspension>
#8      FeatureFileRunner._runWithinTest (package:gherkin/src/feature_file_runner.dart:358:22)
<asynchronous suspension>
#9      FeatureFileRunner._runStep (package:gherkin/src/feature_file_runner.dart:327:16)
<asynchronous suspension>
#10     FeatureFileRunner._runScenario (package:gherkin/src/feature_file_runner.dart:257:13)
<asynchronous suspension>
#11     FeatureFileRunner._runScenarioInZone.<anonymous closure> (package:gherkin/src/feature_file_runner.dart:149:24)
<asynchronous suspension>
     Attachment (text/plain): Failed to take screenshot
_flutter.screenshot: (-32000) Could not capture image screenshot.
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1606:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2078:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2041:14)
#3      VmService.callMethod (package:vm_service/src/vm_service.dart:2031:12)
#4      VMServiceFlutterDriver.screenshot (package:flutter_driver/src/driver/vmservice_driver.dart:338:54)
<asynchronous suspension>
#5      AttachScreenshotOnFailedStepHook.takeScreenshot (package:flutter_gherkin/src/flutter/hooks/attach_screenshot_on_failed_step_hook.dart:28:19)
<asynchronous suspension>
#6      AttachScreenshotOnFailedStepHook.onAfterStep (package:flutter_gherkin/src/flutter/hooks/attach_screenshot_on_failed_step_hook.dart:18:32)
<asynchronous suspension>
#7      AggregatedHook._invokeHooks (package:gherkin/src/hooks/aggregated_hook.dart:92:9)
<asynchronous suspension>
#8      AggregatedHook.onAfterStep (package:gherkin/src/hooks/aggregated_hook.dart:85:7)
<asynchronous suspension>
#9      FeatureFileRunner._runStep (package:gherkin/src/feature_file_runner.dart:338:5)
<asynchronous suspension>
#10     FeatureFileRunner._runScenario (package:gherkin/src/feature_file_runner.dart:257:13)
<asynchronous suspension>
#11     FeatureFileRunner._runScenarioInZone.<anonymous closure> (package:gherkin/src/feature_file_runner.dart:149:24)
<asynchronous suspension>
Step 'And User start selling' did not pass, all remaining steps will be skipped # /Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/features/1_SEL-263,SEL-146 (1).feature:24
Attempting to run step 'And seller login using valid credential in login page' # /Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/features/1_SEL-263,SEL-146 (1).feature:25
   - And seller login using valid credential in login page # /Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/features/1_SEL-263,SEL-146 (1).feature:25 took 0ms
Step 'And seller login using valid credential in login page' did not pass, all remaining steps will be skipped # /Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/features/1_SEL-263,SEL-146 (1).feature:25
FAILED: Scenario [Test] Seller App Onboarding Page - Login Page # /Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/features/1_SEL-263,SEL-146 (1).feature:18
Restarting Flutter app under test
Finished running feature 'Seller apps onboarding' # /Users/fadhlimaulidri/workspace/bukalapak_seller_apps/test_driver/features/1_SEL-263,SEL-146 (1).feature:1
1 scenario (1 failed)
3 steps (1 passed, 1 skipped, 1 failed)
0:00:05.488000
Terminating Flutter app under test
Unhandled exception:
Instance of 'GherkinTestRunFailedException'
#0      GherkinRunner.execute (package:gherkin/src/test_runner.dart:86:9)
<asynchronous suspension>
Failed to stop app
```

<img width="399" alt="Screenshot 2021-08-04 at 17 45 47" src="https://user-images.githubusercontent.com/11204909/128189004-9128b348-7b06-4139-9e66-baf8a3a984a4.png">

**Comment by jonsamwell** [comment]
@fadhlimaulidri  this is a tricky one as is it a native dialog and Flutter gives us no way to interact with native elements.  So what I do is disable notifications on iOS interest relying on testing notifications in the Android version of the app (as their is no user interaction required to enable notifications).

**Comment by fadhlimaulidri** [comment]
do you know how to disable that? i can't find notification setting in my Simulator

**Comment by jonsamwell** [comment]
You will have to pass a flag into the code that manages your app notifications and not call `requestPermission()` on the firebase messaging instance

![image](https://user-images.githubusercontent.com/3694497/128293027-862b4b20-315d-4da6-a7f3-cb1de2d0aff8.png)

You'll probably want to do something like this so you can pass whether or not to disable notifications in when you run the tests

![image](https://user-images.githubusercontent.com/3694497/128293190-52573d88-01b2-4653-82fd-312b5de15412.png)

**Comment by fadhlimaulidri** [comment]
finnaly i use https://github.com/flutter/flutter/issues/12561#issuecomment-780114188 and works
thanks for reply @jonsamwell
