### ISSUE TITLE
Setting up initial test

### ISSUE THREAD

**Issue by DK15** [jonsamwell/flutter_gherkin#15]
Hey Jon,
First of all, great work to have this plugin out. I am looking forward to use this to write automated tests.

For my demo app I would like to have your help in setting up my first test properly.  I tried to follow along instructions in `readme` file but getting an error while running the test. Here's what I've done till now:

**login.feature:**

> Feature: Login
>   User should be able to login successfully after clicking login button.
> 
>   Scenario: User logs in successfully
>     Given I expect the user enters email

**steps.dart:**

```
import 'package:flutter_driver/flutter_driver.dart';
import 'package:flutter_gherkin/flutter_gherkin.dart';

class LoginValidation extends Given1WithWorld<String, FlutterWorld> {

  @override
  Future<void> executeStep(input1) async {
    String input1 = "test@test.com";
    await FlutterDriverUtils.tap(world.driver, find.byValueKey('inputKeyString'));
    await FlutterDriverUtils.enterText(world.driver, find.byValueKey('inputKeyString'), input1);
  }

  @override
  // TODO: implement pattern
  RegExp get pattern => null;

}
```

**app_test.dart:**

```
import 'dart:async';
import 'package:glob/glob.dart';
import 'package:flutter_gherkin/flutter_gherkin.dart';

Future<void> main() {
  final config = FlutterTestConfiguration()
    ..features = [Glob(r"test_driver/features/**.feature")]
    ..reporters = [ProgressReporter(), TestRunSummaryReporter()]
    ..restartAppBetweenScenarios = true
    ..targetAppPath = "test_driver/app.dart"
    ..exitAfterTestRun = true;
  return GherkinRunner().execute(config);
}
```

**Demo app screen:**

![Screen Shot 2019-04-11 at 5 25 06 PM](https://user-images.githubusercontent.com/16548367/55955340-c73fe980-5c7e-11e9-8965-73373bf669a2.png)

When I tried to run this test, I got following exception:
```

[info ] FlutterDriver: Connected to Flutter application.
Running scenario: User logs in successfully # ./test_driver/features/login.feature:3
0 scenario ()
0 step ()
0:00:00.299000
Unhandled exception:
Instance of 'GherkinStepNotDefinedException'
#0      FeatureFileRunner._matchStepToExectuableStep (package:flutter_gherkin/src/feature_file_runner.dart:209:7)
#1      FeatureFileRunner._runStep (package:flutter_gherkin/src/feature_file_runner.dart:133:33)
#2      _AsyncAwaitCompleter.start (dart:async/runtime/lib/async_patch.dart:49:6)
#3      FeatureFileRunner._runStep (package:flutter_gherkin/src/feature_file_runner.dart:130:30)
#4      FeatureFileRunner._runScenario (package:flutter_gherkin/src/feature_file_runner.dart:107:28)
#5      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete (dart:async/runtime/lib/async_patch.dart:28:18)
#12     _completeOnAsyncReturn (dart:async/runtime/lib/async_patch.dart:294:13)
#13     AggregatedReporter.onScenarioStarted (package:flutter_gherkin/src/reporters/aggregated_reporter.dart)
#14     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#18     Future._complete (dart:async/future_impl.dart:473:7)
#19     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#20     _AsyncAwaitCompleter.complete (dart:async/runtime/lib/async_patch.dart:28:18)
#21     _completeOnAsyncReturn (dart:async/runtime/lib/async_patch.dart:294:13)
#22     AggregatedReporter._invokeReporters (package:flutter_gherkin/src/reporters/aggregated_reporter.dart)
#23     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#27     Future._complete (dart:async/future_impl.dart:473:7)
#28     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#29     _AsyncAwaitCompleter.complete (dart:async/runtime/lib/async_patch.dart:28:18)
#30     _completeOnAsyncReturn (dart:async/runtime/lib/async_patch.dart:294:13)
#31     AggregatedReporter.onScenarioStarted.<anonymous closure> (package:flutter_gherkin/src/reporters/aggregated_reporter.dart)
#32     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#33     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#34     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#35     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#36     Future._complete (dart:async/future_impl.dart:473:7)
#37     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#38     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/lib/async_patch.dart:33:20)
#39     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#40     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#41     _runPendingImmediateCallback (dart:isolate/runtime/lib/isolate_patch.dart:115:13)
#42     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:172:5)
```

I am guessing I might have missed some configuration while setting up the `feature` and `steps.dart` files, but would like to know how to fix this error.  My folder structure in project is as below:

![Screen Shot 2019-04-11 at 5 30 21 PM](https://user-images.githubusercontent.com/16548367/55955619-85fc0980-5c7f-11e9-84f1-855bf0834464.png)

Also,  I am curious to know if there's a way to generate step definition file from the cucumber steps itself, like there is a provision in Espresso framework. That would be really handy. Example in case:

![Screen Shot 2019-04-11 at 5 36 56 PM](https://user-images.githubusercontent.com/16548367/55955997-8c3eb580-5c80-11e9-8902-269ae46f4af7.png)

And lastly, if I want to add another step in feature file, how do I write method for that step ? I am basically trying to see if I can achieve something similar to Espresso test framework, wherein,  the stepdef is automatically generated for each step and we just write the code to handle the condition. 

An example pertaining to my demo app would be really helpful for me to get started.

**Comment by Shashikant86** [comment]
Yeah, ran into same issue. @DK15 Looks like you are missing `import` of step file in the `app_test.dart` but i got the same error after importing steps too! @jonsamwell Do you have any solution to this?

**Comment by jonsamwell** [comment]
It simply looks like you have not implemented the regex pattern which is the Gherkin engine runs to match up the step definition with the exectuable step code.  So for your example it would be

```
import 'package:flutter_driver/flutter_driver.dart';
import 'package:flutter_gherkin/flutter_gherkin.dart';

class LoginValidation extends Given1WithWorld<String, FlutterWorld> {

  @override
  Future<void> executeStep(input1) async {
    String input1 = "test@test.com";
    await FlutterDriverUtils.tap(world.driver, find.byValueKey('inputKeyString'));
    await FlutterDriverUtils.enterText(world.driver, find.byValueKey('inputKeyString'), input1);
  }

  @override
  // YOU ARE MISSING THIS REGEX PATTERN
  RegExp get pattern => RegExp(r"I expect the user enters email");

}
```

At the moment there is no way to automatically generate step definition code.  If the popularity increase I would think about doing a VSCode plugin to do this.

**Comment by DK15** [comment]
Thanks for your response @jonsamwell. I added the missing regex pattern but still getting same error as posted earlier.

**Comment by jonsamwell** [comment]
@DK15 could you put a sample project on Github and I'll see why it is not working and fix it or the framework as required.

**Comment by jonsamwell** [comment]
@DK15 Also it might be that you are not importing the step definition class in the configuration object.

```
import 'dart:async';
import 'package:glob/glob.dart';
import 'package:flutter_gherkin/flutter_gherkin.dart';
import 'steps/login_validation_step.dart';

Future<void> main() {
  final config = FlutterTestConfiguration()
    ..stepDefinitions = [LoginValidation()]
    ..features = [Glob(r"test_driver/features/**.feature")]
    ..reporters = [ProgressReporter(), TestRunSummaryReporter()]
    ..restartAppBetweenScenarios = true
    ..targetAppPath = "test_driver/app.dart"
    ..exitAfterTestRun = true;
  return GherkinRunner().execute(config);
}

```

**Comment by DK15** [comment]
@jonsamwell I have imported step def class.  [Here's](https://github.com/DK15/flutter-driver-demo) github link of my project.

**Comment by jonsamwell** [comment]
@DK15 Your app_test.dart file should include the step definitions in the configuration.  Try it with this code.

```
import 'dart:async';
import 'package:glob/glob.dart';
import 'package:flutter_gherkin/flutter_gherkin.dart';
import 'steps/steps.dart';

Future<void> main() {
  final config = FlutterTestConfiguration()
    ..features = [Glob(r"test_driver/features/**.feature")]
    ..stepDefinitions = [LoginValidation()]
    ..reporters = [ProgressReporter(), TestRunSummaryReporter()]
    ..restartAppBetweenScenarios = true
    ..targetAppPath = "test_driver/app.dart"
    ..exitAfterTestRun = true;
  return GherkinRunner().execute(config);
}
```

**Comment by DK15** [comment]
ah, I see what I was missing. Allright, I added missing config and that error is gone. Now I am getting:

`LoginValidation parameter count mismatch. Expect 1 parameters but got 0. Ensure you are extending the correct step class which would be Given`

What parameter is it referring to ?

**Comment by jonsamwell** [comment]
@DK15 at the moment your LoginValidation class is extending a step class that expects a single parameter.  As this class does not need any parameters you should extend from GivenWithWorld instead.

```
import 'package:flutter_driver/flutter_driver.dart';
import 'package:flutter_gherkin/flutter_gherkin.dart';

class LoginValidation extends GivenWithWorld<String, FlutterWorld> {

  @override
  Future<void> executeStep(input1) async {
    String input1 = "test@test.com";
    await FlutterDriverUtils.tap(world.driver, find.byValueKey('inputKeyString'));
    await FlutterDriverUtils.enterText(world.driver, find.byValueKey('inputKeyString'), input1);
  }

  @override
  // YOU ARE MISSING THIS REGEX PATTERN
  RegExp get pattern => RegExp(r"I expect the user enters email");
}
```

**Comment by DK15** [comment]
Got it.   See worked for me:

```
class LoginValidation extends GivenWithWorld<FlutterWorld> {
  LoginValidation()
  : super(StepDefinitionConfiguration()..timeout = Duration(seconds: 10));

  @override
  Future<void> executeStep() async {
    String input1 = "test@test.com";
  //  await world.driver.tap(find.byValueKey('inputKeyString'));
  //  await world.driver.enterText('darshan@test.com');
  //  await FlutterDriverUtils.waitForFlutter(world.driver);
    await FlutterDriverUtils.tap(world.driver, find.byValueKey('inputKeyString'));
    await FlutterDriverUtils.enterText(world.driver, find.byValueKey('inputKeyString'), input1);
  }

  @override
  // TODO: implement pattern
  RegExp get pattern => RegExp(r"I expect the user enters email");

}
```

Thanks @jonsamwell for all your help and support.

**Comment by jonsamwell** [comment]
Great! Let me know if you have any other questions or thoughts.

Jon
