### ISSUE TITLE
Test is freezing on Test Starting Screen When second Test was running

### ISSUE THREAD

**Issue by yahyakara** [jonsamwell/flutter_gherkin#190]
Hi I am new for flutter testing.
I imlemented flutter_gerkhin integration test on our project.I have a  problem , problem is  the first test is running perfectly but while second test was running test is freezing on test start screen and Second test is failing on first step. I don't understand why . Please help me :)

My FlutterTestConfiguration : 
```
void main() {
  executeTestSuite(
    FlutterTestConfiguration.DEFAULT([])
      ..hooks = [ClearPreferencesHook()]
      ..reporters = [
        StdoutReporter(MessageLevel.error)
          ..setWriteLineFn(print)
          ..setWriteFn(print),
        ProgressReporter()
          ..setWriteLineFn(print)
          ..setWriteFn(print),
        TestRunSummaryReporter()
          ..setWriteLineFn(print)
          ..setWriteFn(print),
        JsonReporter(writeReport: (_, __) => Future<void>.value()),
      ]
      ..defaultTimeout = const Duration(minutes: 3)
      ..order = ExecutionOrder.sequential
      ..stepDefinitions = steps
      ..tagExpression = 'not @todo and not @fail and not @debug',
    (world) => app.main(),
  );
}
```

```
My first step is :
       when<FlutterWidgetTesterWorld>(RegExp(r'Wait onboard screen$'),
            (context) async {
              final tester = context.world.rawAppDriver;
              await tester.pumpUntilVisible(OnboardScreen.continueButtonText());
        }),

```
I don't use any restart app function.

```
I/flutter (24267):    √ When Wait onboard screen # :0 took 4042ms
I/flutter (24267):    √ Then Click Onboard contiune # :0 took 123ms
I/flutter (24267):    √ When Wait onboard screen # :0 took 2003ms
I/flutter (24267):    √ Then Click Onboard contiune # :0 took 19ms
I/flutter (24267): PASSED: Scenario demo test 1 # :0
I/flutter (24267): running hook after scenario 'demo test 1'
I/flutter (24267): 00:06 +1: Onboard: demo test 1
I/flutter (24267): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (24267): │ 02:32:08.599 (+0:00:06.459774)
I/flutter (24267): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (24267): │ 💡 appName - com.package.App - 0.1.0 - (1)
I/flutter (24267): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/Sentry  (24267): UncaughtExceptionHandlerIntegration removed.
D/sentry-native(24267): shutting down backend
D/Sentry  (24267): NdkIntegration removed.
D/Sentry  (24267): EnvelopeFileObserverIntegration removed.
D/Sentry  (24267): AppLifecycleIntegration removed.
D/Sentry  (24267): ActivityLifecycleIntegration removed.
D/Sentry  (24267): AppComponentsBreadcrumbsIntegration removed.
D/Sentry  (24267): SystemEventsBreadcrumbsIntegration remove.
D/Sentry  (24267): TempSensorBreadcrumbsIntegration removed.
I/Sentry  (24267): Closing SentryClient.
D/Sentry  (24267): Shutting down
I/Sentry  (24267): Initializing SDK with DSN: 'https://80b9c58f7def462c8e1f6b03b3723292@o1018340.ingest.sentry.io/5984094'
I/Sentry  (24267): GlobalHubMode: 'true'
D/Sentry  (24267): UncaughtExceptionHandlerIntegration enabled: true
D/Sentry  (24267): default UncaughtExceptionHandler class='com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler'
D/Sentry  (24267): UncaughtExceptionHandlerIntegration installed.
D/Sentry  (24267): ShutdownHookIntegration installed.
D/Sentry  (24267): SendCachedEventFireAndForgetIntegration installed.
D/Sentry  (24267): NdkIntegration enabled: true
I/sentry-native(24267): sentry_close() called, but options was empty
I/sentry-native(24267): using database path "/data/data/com.package.App/cache/sentry/.sentry-native"
D/Sentry  (24267): Started processing cached files from /data/user/0/com.package.App/cache/sentry
D/Sentry  (24267): SU isn't found on this Device.
D/Sentry  (24267): Processing dir. /data/user/0/com.package.App/cache/sentry
D/sentry-native(24267): starting backend
D/Sentry  (24267): NdkIntegration installed.
D/Sentry  (24267): Registering EnvelopeFileObserverIntegration for path: /data/user/0/com.package.App/cache/sentry/outbox
D/Sentry  (24267): Processing 0 items from cache dir /data/user/0/com.package.App/cache/sentry
D/Sentry  (24267): EnvelopeFileObserverIntegration installed.
D/Sentry  (24267): SendCachedEventFireAndForgetIntegration installed.
D/Sentry  (24267): File /data/user/0/com.package.App/cache/sentry/outbox is not a File.
D/Sentry  (24267): AnrIntegration enabled: false
D/Sentry  (24267): enableSessionTracking enabled: true
D/Sentry  (24267): enableAppLifecycleBreadcrumbs enabled: true
D/Sentry  (24267): File /data/user/0/com.package.App/cache/sentry/.sentry-native is not a File.
D/Sentry  (24267): Processing file: /data/user/0/com.package.App/cache/sentry/session.json
D/Sentry  (24267): AppLifecycleIntegration installed.
D/Sentry  (24267): File '/data/user/0/com.package.App/cache/sentry/session.json' doesn't match extension expected.
D/Sentry  (24267): ActivityLifecycleIntegration enabled: true
D/Sentry  (24267): ActivityLifecycleIntegration installed.
D/Sentry  (24267): AppComponentsBreadcrumbsIntegration enabled: true
D/Sentry  (24267): Finished processing cached files from /data/user/0/com.package.App/cache/sentry
D/Sentry  (24267): AppComponentsBreadcrumbsIntegration installed.
D/Sentry  (24267): SystemEventsBreadcrumbsIntegration enabled: true
D/Sentry  (24267): Started processing cached files from /data/user/0/com.package.App/cache/sentry/outbox
D/Sentry  (24267): Processing dir. /data/user/0/com.package.App/cache/sentry/outbox
D/Sentry  (24267): Processing 0 items from cache dir /data/user/0/com.package.App/cache/sentry/outbox
D/Sentry  (24267): SystemEventsBreadcrumbsIntegration installed.
D/Sentry  (24267): enableSystemEventsBreadcrumbs enabled: true
D/Sentry  (24267): Finished processing cached files from /data/user/0/com.package.App/cache/sentry/outbox
I/Sentry  (24267): TYPE_AMBIENT_TEMPERATURE is not available.
D/Sentry  (24267): enableSystemEventBreadcrumbs enabled: true
W/Sentry  (24267): Current session is not ended, we'd need to end it.
D/Sentry  (24267): Serializing object:
{"sid":"dd1cbd18-353c-45d5-b153-1b52bf4c7569","did":"933a8948-c2af-4ca8-879f-d4b718897fb5","started":"2021-12-19T23:32:02.253Z","status":"exited","seq":1639956728630,"duration":6.377,"timestamp":"2021-12-19T23:32:08.
630Z","attrs":{"release":"com.package.App@0.1.0+1","environment":""}}
D/Sentry  (24267): Serializing object:
{"sid":"46f06c79-ade1-4902-b28a-f8ccbf65be0e","did":"933a8948-c2af-4ca8-879f-d4b718897fb5","init":true,"started":"2021-12-19T23:32:08.622Z","status":"ok","timestamp":"2021-12-19T23:32:08.622Z","attrs":{"release":"com
.package.App@0.1.0+1","environment":""}}
D/Sentry  (24267): Serializing object:
{"sid":"46f06c79-ade1-4902-b28a-f8ccbf65be0e","did":"933a8948-c2af-4ca8-879f-d4b718897fb5","init":true,"started":"2021-12-19T23:32:08.622Z","status":"ok","timestamp":"2021-12-19T23:32:08.622Z","attrs":{"release":"com
.package.App@0.1.0+1","environment":""}}
D/Sentry  (24267): onEvent fired for EnvelopeFileObserver with event type 8 on path: /data/user/0/com.package.App/cache/sentry/outbox for file b96b9d8d-7859-4077-8a20-ba03e61e0b53.
D/Sentry  (24267): Processing Envelope with 1 item(s)
D/Sentry  (24267): Adding Envelope to offline storage: /data/user/0/com.package.App/cache/sentry/bb340288-8bd3-4cf9-a3d7-9b5a88acc2c9.envelope
I/System.out(24267): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(24267): (HTTPLog)-Static: isSBSettingEnabled false
D/Sentry  (24267): Capturing event: b06f49df42264f33a6a2f4d428c82d22
I/Sentry  (24267): Not possible to read external files directory
D/Sentry  (24267): Captured Envelope is already cached
D/Sentry  (24267): Item 1 is being captured.
I/flutter (24267): Running scenario: demo test 1 # :0
D/Sentry  (24267): Envelope sent successfully.
D/Sentry  (24267): Discarding envelope from cache: /data/user/0/com.package.App/cache/sentry/bb340288-8bd3-4cf9-a3d7-9b5a88acc2c9.envelope
D/Sentry  (24267): Envelope flushed
I/System.out(24267): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(24267): (HTTPLog)-Static: isSBSettingEnabled false
D/Sentry  (24267): Serializing object: {"exception":{"values":[{"mechanism":{"handled":true,"type":"runZonedGuarded"},"stacktrace":{"frames":[{"abs_path":"<asynchronous suspension>"},{"abs_path":"<asynchronous
suspension>"},{"package":"App","abs_path":"package:App/main.dart","colno":9,"filename":"main.dart","function":"_runApp","in_app":true,"lineno":43,"unknown":{"package":"App"}},{"package":"App","abs_path":"pack
age:App/core/injection_container.dart","colno":9,"filename":"injection_container.dart","function":"initDependencies","in_app":true,"lineno":165,"unknown":{"package":"App"}},{"package":"get_it","abs_path":"package
:get_it/get_it_impl.dart","colno":5,"filename":"get_it_impl.dart","function":"_GetItImplementation.registerLazySingleton","in_app":true,"lineno":562,"unknown":{"package":"get_it"}},{"package":"get_it","abs_path":"pac
kage:get_it/get_it_impl.dart","colno":5,"filename":"get_it_impl.dart","function":"_GetItImplementation._register","in_app":true,"lineno":803,"unknown":{"package":"get_it"}},{"package":"get_it","abs_path":"package:get
_it/get_it_impl.dart","colno":18,"filename":"get_it_impl.dart","function":"throwIf","in_app":true,"lineno":7,"unknown":{"package":"get_it"}}]},"type":"ArgumentError","value":"Invalid argument(s): Object/factory with
type Dio is already registered inside GetIt.
"}]},"level":"fatal","timestamp":"2021-12-19T23:32:08.630Z","breadcrumbs":[{"category":"app.lifecycle","data":{"state":"start"},"level":"info","timestamp":"2021-12-19T23:32:08.622Z","type":"session"},{"category":"app
.lifecycle","data":{"state":"foreground"},"level":"info","timestamp":"2021-12-19T23:32:08.623Z","type":"navigation"},{"category":"device.event","data":{"action":"DOCK_EVENT","extras":{"android.intent.extra.DOCK_STATE
":"0"}},"level":"info","timestamp":"2021-12-19T23:32:08.626Z","type":"system"}],"contexts":{"app":{"app_build":"1","app_identifier":"com.package.App","app_name":"appName","app_start_time":"2021-12-19T23:31:57.
909Z","app_version":"0.1.0"},"sentry_dart_runtime":{"name":"Dart","raw_description":"2.14.4 (stable) (Wed Oct 13 11:11:32 2021 +0200) on
\"android_arm64\"","type":"runtime"},"os":{"build":"RP1A.200720.012.G988BXXU8DUF9","kernel_version":"4.19.87-22026739","name":"Android","rooted":false,"version":"11"},"accessibility":{"accessible_navigation":false,"b
old_text":false,"disable_animations":false,"high_contrast":false,"invert_colors":false,"reduce_motion":false},"flutter_context":{"default_route_name":"/","current_lifecycle_state":"resumed"},"culture":{"locale":"en-G
B","is_24_hour_format":true,"timezone":"+03"},"dart_context":{"number_of_processors":8.0,"isolate":"main"},"sentry_flutter_runtime":{"name":"Flutter","compiler":"Dart
VM","type":"runtime"},"device":{"archs":["arm64-v8a","armeabi-v7a","armeabi"],"battery_level":100.0,"battery_temperature":30.4,"boot_time":"2021-12-04T12:40:15.385Z","brand":"samsung","charging":true,"connection_type
":"wifi","family":"SM-G988B","free_memory":4345495552,"free_storage":19319361536,"id":"933a8948-c2af-4ca8-879f-d4b718897fb5","language":"en_GB","low_memory":false,"manufacturer":"samsung","memory_size":11430772736,"m
odel":"SM-G988B","model_id":"RP1A.200720.012","name":"Galaxy S20
Ultra","online":true,"orientation":"portrait","screen_density":2.625,"screen_dpi":420,"screen_height_pixels":2200,"screen_width_pixels":1080,"simulator":false,"storage_size":116230434816,"timezone":"Europe/Istanbul"}
},"dist":"1","environment":"","event_id":"b06f49df42264f33a6a2f4d428c82d22","platform":"other","release":"com.package.App@0.1.0+1","sdk":{"integrations":["isolateErrorIntegration","runZonedGuardedIntegration",
"widgetsFlutterBindingIntegration","flutterErrorIntegration","widgetsBindingIntegration","nativeSdkIntegration","loadAndroidImageListIntegration","loadReleaseIntegration"],"name":"sentry.dart.flutter","packages":[{"n
ame":"pub:sentry","version":"6.2.0"},{"name":"pub:sentry_flutter","version":"6.2.0"},{"name":"maven:io.sentry:sentry","version":"5.3.0"},{"name":"maven:io.sentry:sentry-android-core","version":"5.3.0"},{"name":"ma
D/Sentry  (24267): Serializing object:
{"sid":"46f06c79-ade1-4902-b28a-f8ccbf65be0e","did":"933a8948-c2af-4ca8-879f-d4b718897fb5","started":"2021-12-19T23:32:08.622Z","status":"ok","seq":1639956728670,"errors":1,"timestamp":"2021-12-19T23:32:08.670Z","att
rs":{"release":"com.package.App@0.1.0+1","environment":""}}
D/Sentry  (24267): Envelope sent successfully.
D/Sentry  (24267): Envelope flushed
D/Sentry  (24267): Marking envelope submission result: true
D/Sentry  (24267): File '/data/user/0/com.package.App/cache/sentry/outbox/b96b9d8d-7859-4077-8a20-ba03e61e0b53' is done.
I/flutter (24267):    × When Wait onboard screen # :0 took 12018ms  
I/flutter (24267): Target was not found zero widgets with text "Continue" (ignoring offstage widgets)
I/flutter (24267): #0      GeneralExtendedWidgetTester.pumpUntilVisible (file:///Users/yahya.kara/AndroidStudioProjects/path-flutter/test_screens/utils/general_test_utils.dart:49:28)
I/flutter (24267): <asynchronous suspension>
I/flutter (24267): #1      SampleSteps.steps.<anonymous closure> (file:///Users/yahya.kara/AndroidStudioProjects/path-flutter/integration_test/step_definitions/sample_steps.dart:13:15)
I/flutter (24267): <asynchronous suspension>
I/flutter (24267): #2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart)
I/flutter (24267): <asynchronous suspension>
I/flutter (24267): #3      StepDefinitionGeneric.run.<anonymous closure> (package:gherkin/src/gherkin/steps/step_definition.dart:42:26)
I/flutter (24267): <asynchronous suspension>
I/flutter (24267): #4      Perf.measure (package:gherkin/src/utils/perf.dart:11:14)
I/flutter (24267): <asynchronous suspension>
I/flutter (24267): #5      StepDefinitionGeneric.run (package:gherkin/src/gherkin/steps/step_definition.dart:37:7)
I/flutter (24267): <asynchronous suspension>
I/flutter (24267): #6      GherkinIntegrationTestRu
I/flutter (24267): PASSED: Scenario demo test 1 # :0
I/flutter (24267): running hook after scenario 'demo test 1'
I/flutter (24267): 00:18 +1: Onboard: demo test 1 [E]
I/flutter (24267):   'package:flutter_test/src/binding.dart': Failed assertion: line 785 pos 14: '_pendingExceptionDetails != null': A test overrode FlutterError.onError but either failed to return it to its original
state, or had unexpected additional errors that it could not handle. Typically, this is caused by using expect() before restoring FlutterError.onError.
I/flutter (24267):   dart:core-patch/errors_patch.dart 46:39       _AssertionError._doThrowNew
I/flutter (24267):   dart:core-patch/errors_patch.dart 36:5        _AssertionError._throwNew
I/flutter (24267):   package:flutter_test/src/binding.dart 785:14  TestWidgetsFlutterBinding._runTest.handleUncaughtError
I/flutter (24267):   package:flutter_test/src/binding.dart 790:9   TestWidgetsFlutterBinding._runTest.<fn>
I/flutter (24267):   dart:async/zone.dart 1109:14                  _Zone._processUncaughtError
I/flutter (24267):   dart:async/zone.dart 1312:5                   _CustomZone.handleUncaughtError
I/flutter (24267):   dart:async/future_impl.dart 717:16            Future._propagateToListeners
I/flutter (24267):   dart:async/future_impl.dart 610:5             Future._completeError
I/flutter (24267):   dart:async-patch/async_patch.dart 274:13      _completeOnAsyncError
I/flutter (24267):   package:flutter_test/src/binding.dart         TestWidgetsFlutterBinding._runTestBody
I/flutter (24267):   
I/flutter (24267): Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
I/flutter (24267): For example, 'dart test --chain-stack-traces'.
I/flutter (24267): 00:18 +1 -1: (tearDownAll)
D/Sentry  (24267): onEvent fired for EnvelopeFileObserver with event type 8 on path: /data/user/0/com.package.App/cache/sentry/outbox for file 1cb28a58-584a-4308-afc8-fe1eefc7fe2a.
D/Sentry  (24267): Processing Envelope with 1 item(s)
D/Sentry  (24267): Capturing event: 5773fb4d061d49a1a07b8a4cf5767fa9
I/flutter (24267): 2 scenarios (2 passed)
I/flutter (24267): 5 steps (4 passed, 1 failed)
I/flutter (24267): 0:00:18.944000
I/Sentry  (24267): Not possible to read external files directory
I/flutter (24267): 00:18 +2 -1: Some tests failed.
D/Sentry  (24267): Captured Envelope is already cached
D/Sentry  (24267): Item 1 is being captured.
I/System.out(24267): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(24267): (HTTPLog)-Static: isSBSettingEnabled false
```

Regards

**Comment by jonsamwell** [comment]
Looks like it cannot find any elements with the text "Continue"

```
  × When Wait onboard screen # :0 took 12018ms  
I/flutter (24267): Target was not found zero widgets with text "Continue" (ignoring offstage widgets)
I/flutter (24267): #0      GeneralExtendedWidgetTester.pumpUntilVisible (file:///Users/yahya.kara/AndroidStudioProjects/path-flutter/test_screens/utils/general_test_utils.dart:49:28)
I/flutter (24267): <asynchronous suspension>
I/flutter (24267): #1      SampleSteps.steps.<anonymous closure> (file:///Users/yahya.kara/AndroidStudioProjects/path-flutter/integration_test/step_definitions/sample_steps.dart:13:15)
I/flutter (24267): <asynchronous suspension>
I/flutter (24267): #2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart)
I/flutter (24267): <asynchronous suspension>
I/flutter (24267): #3      StepDefinitionGeneric.run.<anonymous closure> (package:gherkin/src/gherkin/steps/step_definition.dart:42:26)
I/flutter (24267): <asynchronous suspension>
I/flutter (24267): #4      Perf.measure (package:gherkin/src/utils/perf.dart:11:14)
I/flutter (24267): <asynchronous suspension>
I/flutter (24267): #5      StepDefinitionGeneric.run (package:gherkin/src/gherkin/steps/step_definition.dart:37:7)
I/flutter (24267): <asynchronous suspension>
```

**Comment by yahyakara** [comment]
@jonsamwell Yes because test is freezing on test starting screen :/ on second test

**Comment by jonsamwell** [comment]
@yahyakara please can you make a reproducing example of this as I have little to go on here apart from the exception that is raised.

**Comment by yahyakara** [comment]
@jonsamwell  Firstly Thanks a lot for response thank you !  I am taking this issue on our private project, 

The second scenario is not waiting for the first screen of the application, and when the app is on the test start screen, the test starts searching for elements, the frst screen of application can not start while second test starts and it is freezing on test starting ...

Test is freezing this screen 
<img width="349" alt="Screen Shot 2021-12-20 at 18 44 59" src="https://user-images.githubusercontent.com/16323796/146794187-6d4a1ad3-d3df-413a-a7c8-941f35b17237.png">


I am sharing our project main class, I am calling this class for start the app

```
Future<void> main() async {
  if (EnvironmentConfig.envFlutterDriverEnabled) {
    enableFlutterDriverExtension();
  }


  WidgetsFlutterBinding.ensureInitialized();
  await _initAppConfig();

  await SentryFlutter.init(
    (options) {
      return options
        ..environment = EnvironmentConfig.envEnvironmentSuffix
        ..dsn = sentryDsn;
    },
    appRunner: () => _runApp(),
  );
}

Future<void> _runApp() async {
  await Firebase.initializeApp();
  await initDependencies();
  _initStatusBarStyle();
  await _initOrientation();
  await _initLocalNotifications();
  await DateTimeFormatters.init();
  _initializeCoreUiLibrary();
  LocationEventListeners.init();

  runApp(SCommApp());
}

Future<void> _initLocalNotifications() => getIt<NotificationService>().initLocalNotifications();

Future<void> _initAppConfig() async {
  final PackageInfo packageInfo = await PackageInfo.fromPlatform();

  AppConfig(
    environment: EnvironmentConfig.getEnvironmentFromDartDefine(),
    platform: Platform.name,
    appVersion: packageInfo.version,
    buildNumber: packageInfo.buildNumber,
  );

  _printPackageInfo(packageInfo);
}

void _printPackageInfo(PackageInfo packageInfo) async {
  Log.i("${packageInfo.appName} - ${packageInfo.packageName} - ${packageInfo.version} - (${packageInfo.buildNumber})");
}

Future<void> _initOrientation() => SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

void _initStatusBarStyle() {
  // TODO: Check this on ios
  if (io.Platform.isIOS) {
    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.dark);
  } else {
    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light);
  }
}

void _initializeCoreUiLibrary() {
  core_ui_params.initLibrary(
    core_ui_params.CoreUiParams(
      assets: core_ui_params.CoreUiAssetsParams(
        bgAppBarPattern: const AssetImage(AssetsDesignToken.bgAppBarPattern),
        illustrationError: () => Image.asset(AssetsDesignToken.illustrationError),
      ),
      icons: const core_ui_params.CoreUiIconsParams(
        arrowUp: AssetPaintersDesignToken.icArrowUp,
        cart: AssetPaintersDesignToken.icCart,
        close: AssetPaintersDesignToken.icClose,
        closeInAppBar: AssetPaintersDesignToken.icCloseWhite,
        info: AssetPaintersDesignToken.icInfo,
        infoChat: AssetPaintersDesignToken.icInfoChat,
        messagesError: AssetPaintersDesignToken.icMessagesError,
        minusSmall: AssetPaintersDesignToken.icMinusSmall,
        plusSmall: AssetPaintersDesignToken.icPlusSmall,
        search: AssetPaintersDesignToken.icSearch,
        success: AssetPaintersDesignToken.icSuccess,
      ),
      localizationParams: core_ui_params.CoreUiLocalizationParams(
        search: (BuildContext context) => strings.search.localize(context),
        cancel: (BuildContext context) => strings.cancel.localize(context),
        catalogueUnits: (BuildContext context) => strings.catalogueUnits.localize(context),
        emailAddressHint: (BuildContext context) => strings.emailAddressHint.localize(context),
        emptyEmailFieldHint: (BuildContext context) => strings.emptyEmailFieldHint.localize(context),
        emptyPasswordFieldHint: (BuildContext context) => strings.emptyPasswordFieldHint.localize(context),
        errorStateDefaultCTA: (BuildContext context) => strings.errorStateDefaultCTA.localize(context),
        errorStateDefaultSubtitle: (BuildContext context) => strings.errorStateDefaultSubtitle.localize(context),
        errorStateDefaultTitle: (BuildContext context) => strings.errorStateDefaultTitle.localize(context),
        loginPasswordInputFieldHint: (BuildContext context) => strings.loginPasswordInputFieldHint.localize(context),
        onEmailErrorHint: (BuildContext context) => strings.onEmailErrorHint.localize(context),
        passwordSuffixHide: (BuildContext context) => strings.passwordSuffixHide.localize(context),
        passwordSuffixShow: (BuildContext context) => strings.passwordSuffixShow.localize(context),
        phoneNumberHint: (BuildContext context) => strings.phoneNumberHint.localize(context),
        priceFormat: (BuildContext context) => strings.priceFormat.localize(context),
      ),
      navigationServiceGetter: (BuildContext context) => context.read<NavigationService>(),
      colorPalette: core_ui_params.CoreUiColorPalette(
        brandPrimary: ColorsDesignToken.brandPrimary,
        brandPrimaryDark: ColorsDesignToken.brandPrimaryDark,
        brandSecondary: ColorsDesignToken.brandSecondary,
        interactionPrimary: ColorsDesignToken.interactionPrimary,
        interactionPrimaryFeedback: ColorsDesignToken.interactionPrimaryFeedback,
        interactionPrimaryHover: ColorsDesignToken.interactionPrimaryHover,
        interactionTertiary: ColorsDesignToken.interactionTertiary,
        neutralBorder: ColorsDesignToken.neutralBorder,
        neutralDivider: ColorsDesignToken.neutralDivider,
        neutralInactive: ColorsDesignToken.neutralInactive,
        neutralPrimary: ColorsDesignToken.neutralPrimary,
        neutralSecondary: ColorsDesignToken.neutralSecondary,
        neutralSurface: ColorsDesignToken.neutralSurface,
        neutralWhite: ColorsDesignToken.neutralWhite,
        systemError: ColorsDesignToken.systemError,
        systemErrorHighlight: ColorsDesignToken.systemErrorHighlight,
        systemInformation: ColorsDesignToken.systemInformation,
        systemInformationHighlight: ColorsDesignToken.systemInformationHighlight,
        systemSuccess: ColorsDesignToken.systemSuccess,
        systemSuccessHighlight: ColorsDesignToken.systemSuccessHighlight,
        systemWarning: ColorsDesignToken.systemWarning,
        systemWarningHighlight: ColorsDesignToken.systemWarningHighlight,
      ),
    ),
  );
}
```

By the way my email is yahyak.kara@gmail.com

**Comment by jonsamwell** [comment]
OK great.  I would where possible avoid using the raw tester directly instead use the helper functions as I suspect they would avoid things like this as they pump in all the correct places.
