### ISSUE TITLE
type '_TypeError' is not a subtype of type 'Exception'

### ISSUE THREAD

**Issue by snickersv2** [jonsamwell/flutter_gherkin#20]
Hello,

I was running a test and an error happened in the app. However instead of failing the test, the process finished instead.

[warning] FlutterDriver: tap message is taking a long time to complete...
6 scenarios (3 passed, 3 failed)
6 steps (3 passed, 3 failed)
0:03:30.384000
Unhandled exception:
type '_TypeError' is not a subtype of type 'Exception'
#0      FeatureFileRunner._runFeature (package:gherkin/src/feature_file_runner.dart:53:37)
<asynchronous suspension>
#1      FeatureFileRunner.run (package:gherkin/src/feature_file_runner.dart:32:38)
<asynchronous suspension>
#2      GherkinRunner.execute (package:gherkin/src/test_runner.dart:73:45)
<asynchronous suspension>
#3      main (file:///Users/abanv2/Documents/Bitbucket/janus-mobile-app/test_driver/main_page_test.dart:24:26)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

Process finished with exit code 255

Is it possible to just have this as a test failure instead of the entire process crashing?
Thank you.

**Comment by jonsamwell** [comment]
Hi,

Thanks for reporting this.  Do you have any steps to reproduce the
problem?  What step code was running when it crashed?

Thanks

**Comment by snickersv2** [comment]
From what I had gathered, FlutterDriverUtils.tap didn't succeed because it was not able to tap the widget because the widget was not displayed in the first place (this was caused by an error in the app itself).

**Comment by jonsamwell** [comment]
Great, I'll try and reproduce it and fix it over the weekend.
