### ISSUE TITLE
[Bug] JsonReporter with data tables containing null values

### ISSUE THREAD

**Issue by youssef-t** [jonsamwell/flutter_gherkin#225]
Version: flutter_gherkin 3.0.0-rc.9
Flutter 2.10.5
Dart 2.16.3

Hello everyone,

When JsonReporter is used with a feature file containing a data table with null values, the following error is thrown at the start of the test (when the reporter is called for the first time) and test stops:

```
I/flutter (21218): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (21218): The following _CastError was thrown running a test:
I/flutter (21218): type 'Null' is not a subtype of type 'String' in type cast
I/flutter (21218):
I/flutter (21218): When the exception was thrown, this was the stack:
I/flutter (21218): #0      CastIterator.current (dart:_internal/cast.dart:62:36)
I/flutter (21218): #1      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:219:36)
I/flutter (21218): #2      new _List._ofOther (dart:core-patch/array.dart:116:43)
I/flutter (21218): #3      new _List.of (dart:core-patch/array.dart:58:18)
I/flutter (21218): #4      new List.of (dart:core-patch/array_patch.dart:53:20)
I/flutter (21218): #5      Iterable.toList (dart:core/iterable.dart:470:12)
I/flutter (21218): #6      JsonStep.from.<anonymous closure> (package:gherkin/src/reporters/json/json_step.dart:35:25)
I/flutter (21218): #7      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
I/flutter (21218): #8      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
I/flutter (21218): #9      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:206:27)
I/flutter (21218): #10     new _GrowableList.of (dart:core-patch/growable_array.dart:153:28)
I/flutter (21218): #11     new List.of (dart:core-patch/array_patch.dart:51:28)
I/flutter (21218): #12     ListIterable.toList (dart:_internal/iterable.dart:213:44)
I/flutter (21218): #13     JsonStep.from (package:gherkin/src/reporters/json/json_step.dart:40:12)
I/flutter (21218): #14     JsonReporter.onStepStarted (package:gherkin/src/reporters/json/json_reporter.dart:34:57)
I/flutter (21218): #15     AggregatedReporter.onStepStarted.<anonymous closure> (package:gherkin/src/reporters/aggregated_reporter.dart:48:49)
I/flutter (21218): #16     AggregatedReporter.onStepStarted.<anonymous closure> (package:gherkin/src/reporters/aggregated_reporter.dart:48:28)
I/flutter (21218): #17     AggregatedReporter._invokeReporters (package:gherkin/src/reporters/aggregated_reporter.dart:73:21)
I/flutter (21218): <asynchronous suspension>
I/flutter (21218): #18     AggregatedReporter.onStepStarted (package:gherkin/src/reporters/aggregated_reporter.dart:48:5)
I/flutter (21218): <asynchronous suspension>
I/flutter (21218): #19     GherkinIntegrationTestRunner._onBeforeStepRun (package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart:416:5)  
I/flutter (21218): <asynchronous suspension>
I/flutter (21218): #20     GherkinIntegrationTestRunner.runStep (package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart:276:5)
I/flutter (21218): <asynchronous suspension>
I/flutter (21218): #21     _CustomGherkinIntegrationTestRunner.testFeature0.<anonymous closure>.<anonymous closure>
(file:///D:/flutter_project_bug_json_reporter_with_table/basic_app_json_reporter_with_data_table/integration_test/gherkin_suite_test.g.dart:29:13)
I/flutter (21218): <asynchronous suspension>
I/flutter (21218): #22     GherkinIntegrationTestRunner.runScenario.<anonymous closure>
(package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart:185:13)
I/flutter (21218): <asynchronous suspension>
I/flutter (21218): #23     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:15)
I/flutter (21218): <asynchronous suspension>
I/flutter (21218): #24     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:806:5)
I/flutter (21218): <asynchronous suspension>
```

An example of a feature file reproducing the bug:
```gherkin
Feature: Data table with JsonReporter
    Scenario: Data table with JsonReporter
        Given I see the following users
            | name   | age | country |
            | Mike   | 20  | Spain   |
            | Robert |     | Italy   |
```

The step "I see the following users" is defined as following:
```dart
StepDefinitionGeneric<FlutterWidgetTesterWorld> iSeeTheFollowingUsersStepDefinition() =>
    given1<GherkinTable, FlutterWidgetTesterWorld>(
      r'I see the following users',
      (GherkinTable usersTable, StepContext<FlutterWidgetTesterWorld> context) async {
        for (var row in usersTable.rows) {
          // do something with row
          row.columns.forEach((columnValue) => print(columnValue));
        }
      },
    );
```
A repository to reproduce the bug:  [https://github.com/youssef-t/basic-flutter-app-with-flutter-gherkin](https://github.com/youssef-t/basic-flutter-app-with-flutter-gherkin)

*Note:*
I have tried to investigate the source of the bug.  And I think that the JsonReporter class is taking into account null values correctly.
It seems like that the bug comes from Dart itself (if I didn't do something wrong).

**Comment by jonsamwell** [comment]
@youssef-t I can't seem to replicate this in the latest dart_gherkin release.  We'll be updating this library soon, there has been a lot work around the json reporter to quite possibly it was fixed

**Comment by jonsamwell** [comment]
Should be fixed in the latest release `3.0.0-rc.10`

**Comment by youssef-t** [comment]
Thanks a lot !
