### ISSUE TITLE
Missing plugin exception in latest RC

### ISSUE THREAD

**Issue by amitkumar-qa** [jonsamwell/flutter_gherkin#232]
@jonsamwell I suddenly started getting missing plugin error while running flutter gherkin tests.
Till last week it was working fine. Any idea on below error:

`Failure in method: Create Invoice with non integrated stripe account Examples: (1)
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following MissingPluginException was thrown running a test:
MissingPluginException(No implementation found for method
getApplicationDocumentsDirectory on channel
plugins.flutter.io/path_provider)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:115:24)
<asynchronous suspension>
#2      HiveX.initFlutter (package:hive_flutter/src/hive_extensions.dart:12:18)
<asynchronous suspension>
#3      HiveAdapters.registerAllHiveTypeAdapters (package:highlevel_flutter/hl_core/core/hive/hive_types_n_adapters.dart:39:5)
<asynchronous suspension>
#4      main (package:highlevel_flutter/main.dart:51:5)
<asynchronous suspension>
#5      GherkinIntegrationTestRunner.startApp (package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart:225:5)
<asynchronous suspension>
#6      GherkinIntegrationTestRunner.runScenario.<anonymous closure> (package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart:165:13)
<asynchronous suspension>
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:15)
<asynchronous suspension>
#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:806:5)
<asynchronous suspension>

The test description was:
  Create Invoice with non integrated stripe account Examples: (1)
═════════════════════════════════════════════════════════════════

end of failure 17

Failure in method: Verify user can switch location Examples: (1)
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following MissingPluginException was thrown running a test:
MissingPluginException(No implementation found for method
getApplicationDocumentsDirectory on channel
plugins.flutter.io/path_provider)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:115:24)
<asynchronous suspension>
#2      HiveX.initFlutter (package:hive_flutter/src/hive_extensions.dart:12:18)
<asynchronous suspension>
#3      HiveAdapters.registerAllHiveTypeAdapters (package:highlevel_flutter/hl_core/core/hive/hive_types_n_adapters.dart:39:5)
<asynchronous suspension>
#4      main (package:highlevel_flutter/main.dart:51:5)
<asynchronous suspension>
#5      GherkinIntegrationTestRunner.startApp (package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart:225:5)
<asynchronous suspension>
#6      GherkinIntegrationTestRunner.runScenario.<anonymous closure> (package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart:165:13)
<asynchronous suspension>
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:15)
<asynchronous suspension>
#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:806:5)
<asynchronous suspension>

`

**Comment by amitkumar-qa** [comment]
@jonsamwell Closing this issue as it was due to flutter 3, Resolved with flutter 3 upgrade
