### ISSUE TITLE
"I restart the app" step not implemented

### ISSUE THREAD

**Issue by joaofyz** [jonsamwell/flutter_gherkin#272]
We are using the version 3.0.0_RC_17 and when we try to use the "And I restart the app" step we are receiving an UnimplementedError.

```
Exception: UnimplementedError: Unable to restart the app during the test
#0      FlutterWorld.restartApp (package:flutter_gherkin/src/flutter/world/flutter_world.dart:24:5)
#1      restartAppStep.(anonymous closure) (package:flutter_gherkin/src/flutter/steps/restart_app_step.dart:8:27)
#2      restartAppStep.(anonymous closure) (package:flutter_gherkin/src/flutter/steps/restart_app_step.dart:7:5)
#3      Function._apply (dart:core-patch/function_patch.dart:11:73)
#4      Function.apply (dart:core-patch/function_patch.dart:34:12)
#5      GenericFunctionStepDefinition.onRun (package:gherkin/src/gherkin/steps/step_definition_implementations.dart:234:21)
#6      StepDefinitionGeneric.run.(anonymous closure) (package:gherkin/src/gherkin/steps/step_definition.dart:42:32)
#7      StepDefinitionGeneric.run.(anonymous closure) (package:gherkin/src/gherkin/steps/step_definition.dart:38:9)
#8      Perf.measure (package:gherkin/src/utils/perf.dart:11:26)
#9      StepDefinitionGeneric.run (package:gherkin/src/gherkin/steps/step_definition.dart:37:18)
#10     GherkinIntegrationTestRunner.runStep (package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart:362:42)
(asynchronous suspension)
#11     _CustomGherkinIntegrationTestRunner.testFeature0.(anonymous closure).(anonymous closure) (file:///Users/jaferreira/Projects/mobile-daloop/daloop/integration_test/gherkin_suite_test.g.dart:387:22)
(asynchronous suspension)
#12     GherkinIntegrationTestRunner.runScenario.(anonymous closure) (package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart:224:32)
(asynchronous suspension)
#13     testWidgets.(anonymous closure).(anonymous closure) (package:flutter_test/src/widget_tester.dart:170:15)
(asynchronous suspension)
#14     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:833:5)
(asynchronous suspension)
```

**Comment by jonsamwell** [comment]
@joaofyz This show unfortunately be a NotSupportedError rather than an UnimplementedError. This step was created for the flutter_driver version of the library where the app is run and connected to and the steps instrument the app from the outside. So the app can be restarted, the process re-connected to and the test can resume. With the integration_test package that the newer RC version is build upon the app and tests are one process so the app cannot be restarted without restarting the test. What you can do instead is to use a step to reset your application's state which could effectively do the same thing.

There is a crude example of this in the test project but as a hook not a step. Although the code can easily be ported to a step.

https://github.com/jonsamwell/flutter_gherkin/blob/integration_test__package_support/example_with_integration_test/integration_test/gherkin/hooks/reset_app_hook.dart
