### ISSUE TITLE
Errors when launching Flutter Gherkin tests

### ISSUE THREAD

**Issue by russell-sf** [jonsamwell/flutter_gherkin#35]
This is likely an issue with Flutter Driver but I wanted to throw it out there in case you had seen similar problems.

We are experiencing random failures running Flutter Gherkin tests with the following stack trace.

We are seeing 2 specific errors occurring randomly. One run will error out, then a another run will work. Have you seen something similar?

```
dart test_driver/app_test.dart

Starting Flutter app under test 'test_driver/app.dart', this might take a few moments
Unhandled exception:
TimeoutException after 0:01:30.000000: Timeout while waiting for observatory debugger uri
#0      FlutterRunProcessHandler.waitForObservatoryDebuggerUri (package:flutter_gherkin/src/flutter/flutter_run_process_handler.dart:120:29)
<asynchronous suspension>
#1      FlutterAppRunnerHook._runApp (package:flutter_gherkin/src/flutter/hooks/app_runner_hook.dart:66:41)
<asynchronous suspension>
#2      FlutterAppRunnerHook.onBeforeRun (package:flutter_gherkin/src/flutter/hooks/app_runner_hook.dart:19:11)
<asynchronous suspension>
#3      AggregatedHook.onBeforeRun.<anonymous closure> (package:gherkin/src/hooks/aggregated_hook.dart:15:35)
#4      AggregatedHook._invokeHooks (package:gherkin/src/hooks/aggregated_hook.dart:52:21)
<asynchronous suspension>
#5      AggregatedHook.onBeforeRun (package:gherkin/src/hooks/aggregated_hook.dart:15:13)
<asynchronous suspension>
#6      GherkinRunner.execute (package:gherkin/src/test_runner.dart:70:19)
<asynchronous suspension>
#7      main (file:///Users/distiller/project/test_driver/app_test.dart:34:26)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Exited with code 255
```

Then a second error we also are seeing is...
```
dart test_driver/app_test.dart

Starting Flutter app under test 'test_driver/app.dart', this might take a few moments
Running Integration Tests
Running Scenerio - 'Test user can successfully login'
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:49363/91wD5HhROrE=/
[trace] FlutterDriver: Isolate found with number: 474622607
[trace] FlutterDriver: Isolate is not paused. Assuming application is ready.
[info ] FlutterDriver: Connected to Flutter application.
Running scenario: Test user can successfully login # ./test_driver/features/login.feature:5
   × Given I expect the user enters email # ./test_driver/features/login.feature:6 took 10016ms  
TimeoutException after 0:00:10.000000: Future not completed
#0      StepDefinitionGeneric.run.<anonymous closure> (package:gherkin/src/gherkin/steps/step_definition.dart:35:24)
<asynchronous suspension>
#1      Perf.measure (package:gherkin/src/utils/perf.dart:9:26)
<asynchronous suspension>
#2      StepDefinitionGeneric.run (package:gherkin/src/gherkin/steps/step_definition.dart:31:18)
<asynchronous suspension>
#3      FeatureFileRunner._runStep.<anonymous closure> (package:gherkin/src/feature_file_runner.dart:200:16)
<asynchronous suspension>
#4      FeatureFileRunner._runWithinTest (package:gherkin/src/feature_file_runner.dart:218:32)
<asynchronous suspension>
#5      FeatureFileRunner._runStep (package:gherkin/src/feature_file_runner.dart:197:22)
<asynchronous suspension>
#6      FeatureFileRunner._runScenario (package:gherkin/src/feature_file_runner.dart:154:17)
<asynchronous suspension>
#7      FeatureFileRunner._runFeature (package:gherkin/src/feature_file_runner.dart:62:21)
<asynchronous suspension>
#8      FeatureFileRunner.run (package:gherkin/src/feature_file_runner.dart:35:38)
<asynchronous suspension>
#9      GherkinRunner.execute (package:gherkin/src/test_runner.dart:77:45)
<asynchronous suspension>
#10     main (file:///Users/distiller/project/test_driver/app_test.dart:34:26)
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
FAILED: Scenario Test user can successfully login # ./test_driver/features/login.feature:5
Restarting Flutter app under test
Unhandled exception:
Bad state: The client closed with pending request "ext.flutter.driver".
#0      new Client.withoutJson.<anonymous closure> (package:json_rpc_2/src/client.dart:70:24)
#1      _RootZone.run (dart:async/zone.dart:1374:54)
#2      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:150:18)
#3      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:609:39)
#4      Future._propagateToListeners (dart:async/future_impl.dart:665:37)
#5      Future._propagateToListeners (dart:async/future_impl.dart:566:9)
#6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Exited with code 255
```

Have you seen either of these happen?

**Comment by jonsamwell** [comment]
Hi @russell-sf 

Yes I have seen these errors before and there are valid reason for them all.

The first one `Timeout while waiting for observatory debugger uri` is a simple one and very much depends on the machine you are running on.  The observatory debug uri Flutter Driver uses to instrument the app under test so when a observatory debug uri is found it generally means the app is in a state that is ready to test.  Flutter Gherkin will wait for 1 minute 30 seconds for this uri to be posted to the stdout stream from the Flutter process building and launching the app.  So depending on the machine the tests are running on this could happen in 10 seconds on 5 minutes.  To fix this you can set a longer timeout (on our build server this timeout is set to 4 minutes). See https://github.com/jonsamwell/flutter_gherkin#flutterBuildTimeout

The second problem, again is partly due to the speed of the machine.  The default time a step is allowed to run before it is considered failed is 10 seconds.  Obviously if you are setting something up in a step it might run for much longer.  There are two ways to control this timeout.  The first is to change the default step timeout on the configuration object see https://github.com/jonsamwell/flutter_gherkin#step-timeout

The second is to specify the step timeout on the step itself.  This can be done when calling the super constructor of the step.  For example:

```
import 'package:flutter_driver/flutter_driver.dart';
import 'package:gherkin/gherkin.dart';
import 'package:flutter_gherkin/flutter_gherkin.dart';

class TapButtonNTimesStep extends When2WithWorld<String, int, FlutterWorld> {
  TapButtonNTimesStep()
      : super(StepDefinitionConfiguration()..timeout = Duration(seconds: 30));

  @override
  Future<void> executeStep(String input1, int input2) async {
    final locator = find.byValueKey(input1);
    for (var i = 0; i < input2; i += 1) {
      await world.driver.tap(locator, timeout: timeout);
    }
  }

  @override
  RegExp get pattern => RegExp(r"I tap the {string} button {int} times");
}
```

I hope this helps, let me know if you need any further information or help.

Jon

**Comment by jonsamwell** [comment]
Also this on `The client closed with pending request "ext.flutter.driver".` usually means you are not awaiting a future somewhere so the flutter driver is closed and there is still an unawaited future performing an action.

I fixed a small issue with the FlutterDriverUtils.getText method that was missing an await for if you are on an older version of the library this might be your issue.  If not I would check you are awaiting all futures.

**Comment by jonsamwell** [comment]
Note that to debug the first problem of the app not building in time you can enable the flutter process log output via the configuration properties `logFlutterProcessOutput ` & `verboseFlutterProcessLogs` https://github.com/jonsamwell/flutter_gherkin#logFlutterProcessOutput

**Comment by jonsamwell** [comment]
Note that on our build server it can take an age for an Android emulator to boot up and be in a state that Flutter can install the app.  So we used to see a lot of timeout for that observatory uri.  I now have script to wait until the emulator is in a state where Flutter is able to install and run the app.  We now see if succeed every time.  The script below should is pretty much what we use.  Hope if helps.

```
PATH=$PATH:$(FlutterToolPath):$(FlutterToolPath)/cache/dart-sdk/bin/; export PATH

      echo "Updating Android SDK"
      $ANDROID_HOME/tools/bin/sdkmanager --update 1>/dev/null

      echo "Starting adb server"
      $ANDROID_HOME/platform-tools/adb start-server 2>/dev/null

      echo "Installing avd image..."
      echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-29;google_apis_playstore;x86' 1>/dev/null

      echo "Creating avd..."
      $ANDROID_HOME/tools/bin/avdmanager create avd -n test_android_emulator_pixel_xl -k 'system-images;android-29;google_apis_playstore;x86' --force --device 'pixel_xl' 1>/dev/null

      echo "Launching avd..."
      flutter emulators --launch test_android_emulator_pixel_xl

      echo "Started emulator waiting for boot..."

      while [ "$A" != "1" ]; do
              sleep 20
              echo "Waiting for emulator to boot..."
              A=$($ANDROID_HOME/platform-tools/adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
      done

      $ANDROID_HOME/platform-tools/adb devices -l

      echo "Started emulator!"

      echo "Running tests..."

      cd tests/integration

      dart test_harness.dart --targetConfig dev --buildFlavor development --tagExpression "@smoke and not @ignore" --build --no-logFlutterProcessOutput --no-verboseFlutterProcessLogs --buildTimeoutInSeconds 300
   
```

**Comment by jonsamwell** [comment]
Ha, finally, with the step timeout stuff we were seeing lots of issues because of device size. Creating an emulator on a build server and not setting the device type will usually result in a tiny 4 inch screen so it could be (as it was in our case) that the field we wanted to populate was simply not on the screen so the step would just be sat waiting for it appear rather than scroll in into view etc.

**Comment by russell-sf** [comment]
Hi @jonsamwell Thanks for the replies. I've been able to get rid of our timeouts and I moved to the .latest fixed the second error.

Another lingering problem is sometimes when launching the app I get the following error when trying to connect to the flutter driver. This will happen every 3 or 4 runs and will sometimes error for a few runs before working again for a few runs etc. Seems to be timing related again but the error is not helpful.

```
dart test_driver/app_test.dart

Starting Flutter app under test 'test_driver/app.dart', this might take a few moments
Running Integration Tests
Running Scenerio - 'Test user can successfully login'
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:50577/CIktleEANVo=/
[trace] FlutterDriver: Isolate found with number: 170156213
[trace] FlutterDriver: Isolate is not paused. Assuming application is ready.
0 scenario ()
0 step ()
0:00:00.670000
Unhandled exception:
Failed assertion: boolean expression must not be null
#0      FlutterDriver._sendCommand (package:flutter_driver/src/driver/driver.dart:432:17)
<asynchronous suspension>
#1      FlutterDriver.checkHealth (package:flutter_driver/src/driver/driver.dart:449:34)
<asynchronous suspension>
#2      FlutterDriver.connect.checkHealth (package:flutter_driver/src/driver/driver.dart:358:29)
<asynchronous suspension>
#3      FlutterDriver.connect (package:flutter_driver/src/driver/driver.dart:373:44)
<asynchronous suspension>
#4      FlutterTestConfiguration.createFlutterDriver (package:flutter_gherkin/src/flutter/flutter_test_configuration.dart:63:32)
<asynchronous suspension>
#5      FlutterTestConfiguration.createFlutterWorld (package:flutter_gherkin/src/flutter/flutter_test_configuration.dart:71:26)
<asynchronous suspension>
#6      FlutterTestConfiguration.prepare.<anonymous closure> (package:flutter_gherkin/src/flutter/flutter_test_configuration.dart:85:20)
<asynchronous suspension>
#7      FeatureFileRunner._runScenario (package:gherkin/src/feature_file_runner.dart:115:29)
<asynchronous suspension>
#8      FeatureFileRunner._runFeature (package:gherkin/src/feature_file_runner.dart:62:21)
<asynchronous suspension>
#9      FeatureFileRunner.run (package:gherkin/src/feature_file_runner.dart:35:38)
<asynchronous suspension>
#10     GherkinRunner.execute (package:gherkin/src/test_runner.dart:77:45)
<asynchronous suspension>
#11     main (file:///C:/Users/russe/dev/superformula/mgm-mobile-indigo/mgm-mobile-indigo/test_driver/app_test.dart:34:26)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

Here is the output when it works...
```
dart test_driver/app_test.dart

Starting Flutter app under test 'test_driver/app.dart', this might take a few moments
Running Integration Tests
Running Scenerio - 'Test user can successfully login'
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:51182/aBj8fXoPaiQ=/
[trace] FlutterDriver: Isolate found with number: 341006085
[trace] FlutterDriver: Isolate is not paused. Assuming application is ready.
[info ] FlutterDriver: Connected to Flutter application.
Running scenario: Test user can successfully login # test_driver\features\login.feature:5
   √ Given I expect the user enters email # test_driver\features\login.feature:6 took 1471ms
PASSED: Scenario Test user can successfully login # test_driver\features\login.feature:5
Restarting Flutter app under test
Completed Scenerio - 'Test user can successfully login'
1 scenario (1 passed)
1 step (1 passed)
0:00:05.317000
Terminating Flutter app under test
Completed Integration Tests
```

**Comment by jonsamwell** [comment]
Hi @russell-sf <https://github.com/russell-sf>

Could you run it with verbose logging on in the stdout reporter my guess is
one of the boolean configuration properties is being set as null somewhere
which might explain why no features are run.

**Comment by russell-sf** [comment]
```
dart test_driver/app_test.dart

Found feature file '.\test_driver\features\login.feature'
Parsing feature file: '.\test_driver\features\login.feature'
Found 1 feature file(s) to run
Executing features in random order
Starting Flutter app under test 'test_driver/app.dart', this might take a few moments
Running Integration Tests
Attempting to running feature 'Test user can successfully login' # .\test_driver\features\login.feature:1
Running Scenerio - 'Test user can successfully login'
Creating new world for scenerio 'Test user can successfully login' # .\test_driver\features\login.feature:5
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:52460/73m4JkBhjiM=/
[trace] FlutterDriver: Isolate found with number: 1066586053
[trace] FlutterDriver: Isolate is not paused. Assuming application is ready.
Fatal error encountered while running feature 'Test user can successfully login'
Failed assertion: boolean expression must not be null # .\test_driver\features\login.feature:1
Finished running feature 'Test user can successfully login' # .\test_driver\features\login.feature:1
0 scenario ()
0 step ()
0:00:00.605000
Unhandled exception:
Failed assertion: boolean expression must not be null
#0      FlutterDriver._sendCommand (package:flutter_driver/src/driver/driver.dart:432:17)
<asynchronous suspension>
#1      FlutterDriver.checkHealth (package:flutter_driver/src/driver/driver.dart:449:34)
<asynchronous suspension>
#2      FlutterDriver.connect.checkHealth (package:flutter_driver/src/driver/driver.dart:358:29)
<asynchronous suspension>
#3      FlutterDriver.connect (package:flutter_driver/src/driver/driver.dart:373:44)
<asynchronous suspension>
#4      FlutterTestConfiguration.createFlutterDriver (package:flutter_gherkin/src/flutter/flutter_test_configuration.dart:63:32)
<asynchronous suspension>
#5      FlutterTestConfiguration.createFlutterWorld (package:flutter_gherkin/src/flutter/flutter_test_configuration.dart:71:26)
<asynchronous suspension>
#6      FlutterTestConfiguration.prepare.<anonymous closure> (package:flutter_gherkin/src/flutter/flutter_test_configuration.dart:85:20)
<asynchronous suspension>
#7      FeatureFileRunner._runScenario (package:gherkin/src/feature_file_runner.dart:115:29)
<asynchronous suspension>
#8      FeatureFileRunner._runFeature (package:gherkin/src/feature_file_runner.dart:62:21)
<asynchronous suspension>
#9      FeatureFileRunner.run (package:gherkin/src/feature_file_runner.dart:35:38)
<asynchronous suspension>
#10     GherkinRunner.execute (package:gherkin/src/test_runner.dart:77:45)
<asynchronous suspension>
#11     main (file:///C:/Users/russe/dev/superformula/mgm-mobile-indigo/mgm-mobile-indigo/test_driver/app_test.dart:34:26)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by jonsamwell** [comment]
This happens intermittently? Doesn't appear to be the flutter gherkin code
rather something when the flutter driver is connecting to your app.

Could you paste the content of the flutter driver log file.

Also what version of flutter are you running? Are you able to do a repo
where this always happens then I can investigate further. Also does this
happen if you run the example in the flutter gherkin repository of just on
your project?

Thanks

Jon

**Comment by jonsamwell** [comment]
Maybe something to do with this?

https://github.com/flutter/flutter/issues/36086

**Comment by russell-sf** [comment]
Hmm. That's exactly the version we are pinned to. Flutter version 1.7.8+hotfix.3
I will see about getting the flutter upgraded. Hopefully its better on .latest

I'll let you know. Thanks!

**Comment by jonsamwell** [comment]
Great, yeah let me know.  I'll close the issue for now but if it is still happening after the upgrade please re-open and we can investigate further.

**Comment by russell-sf** [comment]
I found the issue we were having with those last errors.

Our init code is async so our main looks like this...

```
void main() async {
  // Enables the test driver extension. MUST BE FIRST!!!
  enableFlutterDriverExtension();

  // Call our app init code in test mode.
  await app.initApp(testMode: true);

  // We can alter the configuration as needed to run the tests.
  // We may want to setup several testing configurations here.

  // Call the createApp method.
  app.createApp();
}
```

Since this effectively defers the call to app.createApp, main exits and the flutter driver starts up and starts running tests. Problem is the awaited call may still be in flight so the app isn't ready to communicate with the driver and the driver errors out.

To get around this we add some artificial delay to our flutter driver before it starts running tests to give the awaited code time to complete and call runApp.

There is an open issue on flutter driver here.
https://github.com/flutter/flutter/issues/41029

Things are working pretty well now.
