### ISSUE TITLE
Cannot verify text of RichText widget

### ISSUE THREAD

**Issue by longk15t** [jonsamwell/flutter_gherkin#48]
Hi @jonsamwell , have a good day.
I tried to used our dependency to verify text of a RichText widget
This is how the RichText looks like

```
RichText(
    key: ValueKey("richtext"),
    text: TextSpan(
        text: 'main rich text ',
        style: DefaultTextStyle.of(context).style,
        children: <TextSpan>[
            TextSpan(
                 style: TextStyle(fontSize: 18, color: Colors.red),
                 text: 'Text span 1 '
            ),
            TextSpan(
                 style: TextStyle(fontSize: 15, color: Colors.blue),
                 text: 'Text span 2'
             )
         ]
    )
)
```

This is feature step ( I just use the format of predefined step)
`Then I expect the "richtext" to be "main rich text Text span 1 Text span 2"`

This is the output
```× Then I expect the "richtext" to be "main rich text Text span1 Text span 2" # ./../test_driver/features/add_subtract.feature:7 took 62ms  
Exception: DriverError: Error in Flutter application: Uncaught extension error while executing get_text: type 'RichText' is not a subtype of type 'Text'
#0      FlutterDriverExtension._getText (package:flutter_driver/src/extension/extension.dart:537:16)
<asynchronous suspension>
#1      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:204:53)
#2      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:518:32)
<asynchronous suspension>
#3      _runExtension (dart:developer-patch/developer.dart:86:23)

Original error: null
Original stack trace:
null

#0      FlutterDriver._sendCommand (package:flutter_driver/src/driver/driver.dart:456:7)
<asynchronous suspension>
#1      FlutterDriver.getText (package:flutter_driver/src/driver/driver.dart:713:41)
#2      FlutterDriverUtils.getText (package:flutter_gherkin/src/flutter/utils/driver_utils.dart:46:31)
<asynchronous suspension>
#3      ThenExpectElementToHaveValue.executeStep (package:flutter_gherkin/src/flutter/steps/then_expect_element_to_have_value_step.dart:24:45)
#4      StepDefinition2.onRun (package:gherkin/src/gherkin/steps/step_definition_implementations.dart:52:13)
#5      StepDefinitionGeneric.run.<anonymous closure> (package:gherkin/src/gherkin/steps/step_definition.dart:35:30)
#6      Perf.measure (package:gherkin/src/utils/perf.dart:11:26)
#7      StepDefinitionGeneric.run (package:gherkin/src/gherkin/steps/step_definition.dart:31:18)
#8      FeatureFileRunner._runStep.<anonymous closure> (package:gherkin/src/feature_file_runner.dart:210:16)
#9      FeatureFileRunner._runWithinTest (package:gherkin/src/feature_file_runner.dart:228:32)
#10     FeatureFileRunner._runStep (package:gherkin/src/feature_file_runner.dart:207:22)
<asynchronous suspension>
#11     FeatureFileRunner._runScenario (package:gherkin/src/feature_file_runner.dart:164:17)
<asynchronous suspension>
#12     FeatureFileRunner._runFeature (package:gherkin/src/feature_file_runner.dart:62:21)
<asynchronous suspension>
#13     FeatureFileRunner.run (package:gherkin/src/feature_file_runner.dart:35:38)
#14     GherkinRunner.execute (package:gherkin/src/test_runner.dart:77:45)
<asynchronous suspension>
#15     main (file:///Users/long.tranhoang/FlutterAppTest/FlutterApp/test_driver/app_test.dart:15:26)
#16     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

I think the point is `Uncaught extension error while executing get_text: type 'RichText' is not a subtype of type 'Text'`. Why does this happen ? Do we have any solution for this ?
Thanks in advanced.

**Comment by jonsamwell** [comment]
Yes this is a known limitation of Flutter driver at the moment in that it can only retrieve text from 'Text' widgets see https://github.com/flutter/flutter/issues/16013

However, they have closed this bug without a satisfactory conclusion.  It would be good if you file a bug against the Flutter report for the driver not being able to get the text from TextSpan or RichText widgets.  I will upvote and comment on it too.  It's pretty poor from there side and leads to a bad developer experience.

Let me know the bug url

**Comment by longk15t** [comment]
@jonsamwell the last comment in https://github.com/flutter/flutter/issues/21961 looks potential
```
expect(
  find.byWidgetPredicate((Widget widget) =>
      widget is RichText &&
      widget.text.toPlainText() == 'textToCompare'),
  findsOneWidget,
);
```
is it possible to use in a step definition class ?

**Comment by longk15t** [comment]
@jonsamwell reported an issue https://github.com/flutter/flutter/issues/48797

**Comment by jonsamwell** [comment]
Will be fixed in Flutter when this PR lands https://github.com/flutter/flutter/pull/48809
