### ISSUE TITLE
Issue after upgrading to latest Flutter stable release (1.17.0)

### ISSUE THREAD

**Issue by jonjon1123** [jonsamwell/flutter_gherkin#67]
It looks like there is something wrong after updating to Flutter 1.17.0 (see below error). I tried updating to `flutter_gherkin: ^1.1.8-rc.2`, but I still get the below error.
```
Flutter run key commands.
r Hot reload.
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on AOSP on IA Emulator is available at: http://127.0.0.1:54972/d5TT3rM9KFU=/
VMServiceFlutterDriver Connecting to Flutter application at http://127.0.0.1:54972/d5TT3rM9KFU=/
VMServiceFlutterDriver Isolate found with number: 2621319811561611
VMServiceFlutterDriver Isolate is not paused. Assuming application is ready.
JSON-RPC error -32601 (method not found): Method not found
DriverError: Failed to fulfill GetHealth due to remote error
Original error: JSON-RPC error -32601 (method not found): Method not found
Original stack trace:
package:json_rpc_2/src/client.dart 110:64                                   Client.sendRequest
package:json_rpc_2/src/peer.dart 79:15                                      Peer.sendRequest
package:vm_service_client/src/scope.dart 64:23                              Scope.sendRequestRaw
package:vm_service_client/src/isolate.dart 361:19                           VMIsolateRef.invokeExtension
package:flutter_driver/src/driver/vmservice_driver.dart 323:63              VMServiceFlutterDriver.sendCommand
package:flutter_driver/src/driver/driver.dart 174:34                        FlutterDriver.checkHealth
package:flutter_driver/src/driver/vmservice_driver.dart 217:29              VMServiceFlutterDriver.connect.checkHealth
package:flutter_driver/src/driver/vmservice_driver.dart 232:44              VMServiceFlutterDriver.connect
===== asynchronous gap ===========================
package:flutter_driver/src/driver/driver.dart 148:35                        FlutterDriver.connect
package:flutter_gherkin/src/flutter/flutter_test_configuration.dart 118:34  FlutterTestConfiguration._attemptDriverConnection
package:flutter_gherkin/src/flutter/flutter_test_configuration.dart 75:18   FlutterTestConfiguration.createFlutterDriver
package:flutter_gherkin/src/flutter/flutter_test_configuration.dart 81:26   FlutterTestConfiguration.createFlutterWorld
package:flutter_gherkin/src/flutter/flutter_test_configuration.dart 95:20   FlutterTestConfiguration.prepare.<fn>
package:gherkin/src/feature_file_runner.dart 167:42                         FeatureFileRunner._runScenario
===== asynchronous gap ===========================
package:gherkin/src/feature_file_runner.dart 118:30                         FeatureFileRunner._runScenarioInZone.<fn>
dart:async/zone.dart 1184:13                                                _rootRun
dart:async/zone.dart 1077:19                                                _CustomZone.run
dart:async/zone.dart 1619:10                                                _runZoned
dart:async/zone.dart 1608:12                                                runZonedGuarded
dart:async/zone.dart 1536:12                                                runZoned
package:gherkin/src/feature_file_runner.dart 116:5                          FeatureFileRunner._runScenarioInZone
package:gherkin/src/feature_file_runner.dart 63:21                          FeatureFileRunner._runFeature
===== asynchronous gap ===========================
package:gherkin/src/feature_file_runner.dart 36:38                          FeatureFileRunner.run
package:gherkin/src/test_runner.dart 77:45                                  GherkinRunner.execute
===== asynchronous gap ===========================
tests\all_test.dart 8:26                                                    main
dart:isolate-patch/isolate_patch.dart 301:19                                _startIsolate.<fn>
dart:isolate-patch/isolate_patch.dart 168:12                                _RawReceivePortImpl._handleMessage


JSON-RPC error -32601 (method not found): Method not found
Unhandled exception:
Bad state: No element
#0      List.last (dart:core-patch/growable_array.dart:224:5)
#1      JsonFeature.currentScenario (package:gherkin/src/reporters/json/json_feature.dart:33:22)
#2      JsonReporter.onException (package:gherkin/src/reporters/json/json_reporter.dart:40:10)
#3      AggregatedReporter.onException.<anonymous closure> (package:gherkin/src/reporters/aggregated_reporter.dart:58:30)
#4      AggregatedReporter._invokeReporters (package:gherkin/src/reporters/aggregated_reporter.dart:70:21)
<asynchronous suspension>
#5      AggregatedReporter.onException (package:gherkin/src/reporters/aggregated_reporter.dart:57:11)
#6      FeatureFileRunner._runScenarioInZone.<anonymous closure> (package:gherkin/src/feature_file_runner.dart:131:23)
#7      _rootRunBinary (dart:async/zone.dart:1208:13)
#8      _RootZone.runBinary (dart:async/zone.dart:1445:12)
#9      runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1591:19)
#10     _CustomZone.handleUncaughtError (dart:async/zone.dart:1059:19)
#11     Future._propagateToListeners (dart:async/future_impl.dart:598:16)
#12     Future._completeError (dart:async/future_impl.dart:534:5)
#13     Future.timeout.<anonymous closure> (dart:async/future_impl.dart:785:16)
#14     _rootRunBinary (dart:async/zone.dart:1204:38)
#15     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#16     _FutureListener.handleError (dart:async/future_impl.dart:155:20)
#17     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
#18     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
#19     Future._propagateToListeners (dart:async/future_impl.dart:609:9)
#20     Future._completeError (dart:async/future_impl.dart:534:5)
#21     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
#22     Scope.sendRequestRaw (package:vm_service_client/src/scope.dart)
<asynchronous suspension>
#23     VMIsolateRef.invokeExtension (package:vm_service_client/src/isolate.dart:361:19)
#24     VMServiceFlutterDriver.sendCommand (package:flutter_driver/src/driver/vmservice_driver.dart:323:63)
#25     FlutterDriver.checkHealth (package:flutter_driver/src/driver/driver.dart:174:34)
#26     VMServiceFlutterDriver.connect.checkHealth (package:flutter_driver/src/driver/vmservice_driver.dart:217:29)
#27     VMServiceFlutterDriver.connect (package:flutter_driver/src/driver/vmservice_driver.dart:232:44)
<asynchronous suspension>
#28     FlutterDriver.connect (package:flutter_driver/src/driver/driver.dart:148:35)
#29     FlutterTestConfiguration._attemptDriverConnection (package:flutter_gherkin/src/flutter/flutter_test_configuration.dart:118:34)
#30     FlutterTestConfiguration.createFlutterDriver (package:flutter_gherkin/src/flutter/flutter_test_configuration.dart:75:18)
#31     FlutterTestConfiguration.createFlutterWorld (package:flutter_gherkin/src/flutter/flutter_test_configuration.dart:81:26)
#32     FlutterTestConfiguration.prepare.<anonymous closure> (package:flutter_gherkin/src/flutter/flutter_test_configuration.dart:95:20)
#33     FeatureFileRunner._runScenario (package:gherkin/src/feature_file_runner.dart:167:42)
<asynchronous suspension>
#34     FeatureFileRunner._runScenarioInZone.<anonymous closure> (package:gherkin/src/feature_file_runner.dart:118:30)
#35     _rootRun (dart:async/zone.dart:1184:13)
#36     _CustomZone.run (dart:async/zone.dart:1077:19)
#37     _runZoned (dart:async/zone.dart:1619:10)
#38     runZonedGuarded (dart:async/zone.dart:1608:12)
#39     runZoned (dart:async/zone.dart:1536:12)
#40     FeatureFileRunner._runScenarioInZone (package:gherkin/src/feature_file_runner.dart:116:5)
#41     FeatureFileRunner._runFeature (package:gherkin/src/feature_file_runner.dart:63:21)
<asynchronous suspension>
#42     FeatureFileRunner.run (package:gherkin/src/feature_file_runner.dart:36:38)
#43     GherkinRunner.execute (package:gherkin/src/test_runner.dart:77:45)
<asynchronous suspension>
#44     main
#45     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by jonsamwell** [comment]
Hi, you will need to update to flutter gherkin 1.1.8 that I released
yesterday. This supercedes the 1.1.8-rc releases.

This should be the first point of call, if the issue is not resolved please
provide a way to reproduce the issue.

Thanks

Jon

**Comment by jonsamwell** [comment]
@jonjon1123 This is the version you should upgrade too https://pub.dev/packages/flutter_gherkin/versions/1.1.8

Oddly it looks like the underlying problem is that the `getHealth` flutter driver call did not work for some reason.  Did you call `enableFlutterDriverExtension()` in the flutter app so that the driver can talk to the running app?

Also there is a small issue here with the JsonReporter logging exceptions when no scenario has been run.  I'll get that sorted in the core gherkin repo (https://github.com/jonsamwell/dart_gherkin)

Let me know how you get on with v1.1.8

**Comment by jonjon1123** [comment]
@jonsamwell I changed to use `flutter_gherkin: ^1.1.8` and I still see the issue. I also checked my flutter app and I do call `enableFlutterDriverExtension()` as the very first line in `main()`.

I dug a little deeper and figured out that this exception only occurs when I try to run tests on an emulator. They just fine on a actual physical device.

**Comment by jonsamwell** [comment]
Hmm that is interesting. Could you enable the verbose logging in the
StdoutReporter and verbose flutter driver logging `logFlutterProcessOutput`
then post the output here. If you can get a simple test that fails I can
have a look at it.

Thanks

**Comment by DiegoNovati** [comment]
Same problem and same stack error: the project works perfectly with the iPhone simulator but fails with the Android emulator.

**Comment by jonsamwell** [comment]
What Android OS version is the emulator running. Could you try running the
example tests in the repository to give us a baseline to work off.

Also please provide verbose doctor info.

Any further information would be great as before the library is released
tests get run on emulators to check everything is working.

Thanks

Jon

**Comment by jonsamwell** [comment]
@jonjon1123 @DiegoNovati I've fixed the issue with the JsonReporter with the latest release (1.1.8+1) however, I think the error you are seeing is a flutter driver one and not because of this library as it appears the initial connection of the flutter driver to the app is failing due to an RPC (getHealth) error.  Could you try a simple direct flutter driver test without using gherkin and see if the issue is still there?

**Comment by jonsamwell** [comment]
@jonjon1123 @DiegoNovati I've investigated this a bit more today and came across https://github.com/flutter/flutter/issues/42433 which I think might be something to do with this. 
 Interestingly, this has started happening today on our build server.  

For reference we are testing on Android emulators with this configuration `system-images;android-29;google_apis_playstore;x86`.  Changing the configuration to `system-images;android-29;google_apis_playstore;x86_64` does not work but changing to `system-images;android-29;default;x86_64` seems to work!

Are you seeing this on your build server or can you reproduce this locally?  Please try the `system-images;android-29;default;x86_64` and let me know if you still experience the issue.

For reference this is how we create an Android emulator and run our test on our build server (we use Azure devops)

```
PATH=$PATH:$(FlutterToolPath):$(FlutterToolPath)/cache/dart-sdk/bin/; export PATH

echo "Updating Android SDK"
$ANDROID_HOME/tools/bin/sdkmanager --update 1>/dev/null

echo "Starting adb server"
$ANDROID_HOME/platform-tools/adb start-server 2>/dev/null

echo "Installing avd image..."
echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-29;default;x86_64' 1>/dev/null

echo "Creating avd..."
$ANDROID_HOME/tools/bin/avdmanager create avd -n test_android_emulator_pixel_xl -k 'system-images;android-29;default;x86_64' --force --device 'pixel_xl' 1>/dev/null

echo "Launching avd..."
flutter emulators --launch test_android_emulator_pixel_xl

echo "Started emulator waiting for boot..."

while [ "$A" != "1" ]; do
              sleep 20
              echo "Waiting for emulator to boot..."
              A=$($ANDROID_HOME/platform-tools/adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
done

$ANDROID_HOME/platform-tools/adb devices -l

echo "Started emulator!"

echo "Running tests..."

flutter pub get

cd tests/integration

dart test_harness.dart --targetConfig dev --buildFlavor development --tagExpression "@smoke and not @ignore" --no-logFlutterProcessOutput --no-verboseFlutterProcessLogs --buildTimeoutInSeconds 300

```

**Comment by jonjon1123** [comment]
The tests I have written all require a user to be signed in via Firebase auth (which is backed by Google APIs), so I can't try out `system-images;android-29;default;x86_64` as that image doesn't have any Google APIs or services. :( I am reproducing all of this locally.

**Comment by jonsamwell** [comment]
@jonjon1123 I'm 95% sure the error you are experiencing is an issue with the driver connecting to an Android emulator with the google apis.  So I would file a bug with the Flutter team.  That being said I have made this library retry when a driver connection attempt fails.  Give that a shot and see if the retry is able to connect on additional tries (it'll wait for 2 seconds between connection attempts which is configurable via `flutterDriverReconnectionDelay` property).

I've added the methods `onBeforeFlutterDriverConnect` & `onAfterFlutterDriverConnect` on the `FlutterTestConfiguration` so if the latest fails I would make the `onBeforeFlutterDriverConnect` wait for say 20 seconds to see if that makes a difference for the driver to be able to connect (as I think it is a most likely a timing issue on Flutter driver's side).  If it works I would keep reducing the wait time until you have the balance of a successful connection / speed.

So your config would look something like this:

```
import 'dart:async';
import 'package:flutter_gherkin/flutter_gherkin.dart';
import 'package:gherkin/gherkin.dart';
import 'package:glob/glob.dart';
import 'hooks/hook_example.dart';
import 'steps/colour_parameter.dart';
import 'steps/given_I_pick_a_colour_step.dart';
import 'steps/tap_button_n_times_step.dart';

Future<void> main() {
  final config = FlutterTestConfiguration()
    ..features = [Glob('features//**.feature')]
    ..reporters = [
      ProgressReporter(),
      TestRunSummaryReporter(),
      JsonReporter(path: './report.json'),
      FlutterDriverReporter(
        logErrorMessages: true,
        logInfoMessages: true,
        logWarningMessages: true,
      ),
    ]
    ]
    ..stepDefinitions = [
      TapButtonNTimesStep(),
      GivenIPickAColour(),
    ]
    ..restartAppBetweenScenarios = true
    ..targetAppWorkingDirectory = '../'
    ..targetAppPath = 'test_driver/app.dart'
    ..flutterDriverMaxConnectionAttempts = 3
    ..flutterDriverReconnectionDelay = const Duration(seconds: 2)
    ..onBeforeFlutterDriverConnect =
        (() async => await Future<void>.delayed(const Duration(seconds: 20)))
    ..exitAfterTestRun = true; // set to false if debugging to exit cleanly

  return GherkinRunner().execute(config);
}

```

Let me know how you get on.

**Comment by jonjon1123** [comment]
@jonsamwell I tried your suggestions. The retries didn't have any impact. The same stacktrace was immediately thrown. However, adding `..onBeforeFlutterDriverConnect = (() async => await Future<void>.delayed(const Duration(seconds: 20)))` did fix the issue! So it seems like some kind of issue where the emulator is reporting it is ready for a driver connection, but it really isn't. Adding that delay seems to give the emulator time to establish itself and get ready for a driver connection.

**Comment by jonsamwell** [comment]
@jonjon1123 glad that fixed it.  Did you try lower wait values to see smallest time needed?

Could you post the logs for the retries so I can see the issue - would have thought that would have tried 3 times to connect so something must be up there that needs fixing

Thanks,

**Comment by jonsamwell** [comment]
@DiegoNovati does the fix work for you?

**Comment by DiegoNovati** [comment]
Hi, 
it seems that the fix solved the problem with Android.

Thank you

Diego

**Comment by jonjon1123** [comment]
@jonsamwell Well, I am not sure what happened, but now I am able to remove `..onBeforeFlutterDriverConnect = (() async => await Future<void>.delayed(const Duration(seconds: 20)))` and the retries handle the failed driver connections just fine. I am not sure what I did wrong the first time I was testing the retries, but now they seem to work as expected:
```
Starting Flutter app under test 'test_driver/app.dart', this might take a few moments
Invoking from working directory `../` command: `flutter run --target=test_driver/app.dart`
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching test_driver/app.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...                              5.3s
√ Built build\app\outputs\apk\debug\app-debug.apk.
Syncing files to device Android SDK built for x86...               310ms

Flutter run key commands.
r Hot reload.
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:56491/ThQwZc2W0gU=/
VMServiceFlutterDriver Connecting to Flutter application at http://127.0.0.1:56491/ThQwZc2W0gU=/
VMServiceFlutterDriver Isolate found with number: 2024716238961587
VMServiceFlutterDriver Isolate is not paused. Assuming application is ready.
Fluter driver error connecting to application at `http://127.0.0.1:56491/ThQwZc2W0gU=/`, retrying after delay of 0:00:02.000000
VMServiceFlutterDriver Connecting to Flutter application at http://127.0.0.1:56491/ThQwZc2W0gU=/
VMServiceFlutterDriver Isolate found with number: 2024716238961587
VMServiceFlutterDriver Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver Connected to Flutter application.
Running scenario: Simple pin score update # features\pin_update.feature:5
```

**Comment by jonsamwell** [comment]
Thanks for the logs @jonjon1123 it looks to be working as I expected and should be quicker than just waiting 20 seconds!

If you are happy I'll close this issue.  I would implore you both @jonjon1123 & @DiegoNovati to comment on the Flutter issue (https://github.com/flutter/flutter/issues/42433) to get the Flutter team to actually fix the issue with the driver being flaky on Android emulators with google_apis.

**Comment by jonjon1123** [comment]
@jonsamwell Yep, I am good to close the issue! I will def comment on that flutter issue. Thanks for all your help and thanks for such an awesome library!

**Comment by jonsamwell** [comment]
No problem @jonjon1123 glad you are finding it useful.
