### ISSUE TITLE
is possible run 'flutter drive --target=test_driver/app.dart' ? 

### ISSUE THREAD

**Issue by juanagu** [jonsamwell/flutter_gherkin#75]
Hello, I'm trying to run the test using 'flutter drive --target=test_driver/app.dart' command, but I had the next error:

**Environment:**
_OS_: OSX
_Version_: flutter_gherkin: 1.1.8+2

_Flutter doctor:_

```
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Mac OS X 10.15.4 19E287, locale en-AR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.46.1)
[✓] Connected device (3 available)
```
**Error:**
`
Unhandled exception:
FileSystemException: Directory listing failed, path = './features/' (OS Error: No such file or directory, errno = 2)
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:37:68)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      _ListTreeNode.listSync (package:glob/src/list_tree.dart:402:12)
#3      _ListTreeNode.listSync.<anonymous closure> (package:glob/src/list_tree.dart:410:35)
#4      ExpandIterator.moveNext (dart:_internal/iterable.dart:487:31)
#5      ExpandIterator.moveNext (dart:_internal/iterable.dart:481:32)
#6      new List.from (dart:core-patch/array_patch.dart:50:19)
#7      new List.of (dart:core-patch/array_patch.dart:68:17)
#8      Iterable.toList (dart:core/iterable.dart:404:12)
#9      ListTree.listSync (package:glob/src/list_tree.dart:201:37)
#10     Glob.listSync (package:glob/glob.dart:151:22)
#11     GherkinRunner.execute (package:gherkin/src/test_runner.dart:43:31)
#12     main (file:///Users/juanagu/imperial_tracking_app/test_driver/app_test.dart:43:26)
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Stopping application instance.
Driver tests failed: 255
`

**Comment by juanagu** [comment]
My error I was copy the     `..features = [Glob('features//**.feature')]` from the example. The correct conf to run with flutter driver from the root of project is  `..features = [Glob('./test_driver/features//**.feature')]`
