### ISSUE TITLE
Error waiting for no transient callbacks from Flutter driver: `Failed assertion: boolean expression must not be null`

### ISSUE THREAD

**Issue by comerc** [jonsamwell/flutter_gherkin#93]
```
$ dart app_test.dart 
Starting Flutter app under test 'test_driver/app.dart', this might take a few moments
before run hook
VMServiceFlutterDriver Connecting to Flutter application at http://127.0.0.1:33783/7QZcLiOzt4E=/
VMServiceFlutterDriver Isolate found with number: 4009575061655919
VMServiceFlutterDriver Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver Connected to Flutter application.
running hook before scenario 'User can navigate back from page two'
Running scenario: User can navigate back from page two # ./features/back_navigation.feature:3
   √ Given I expect the "counter" to be "0" # ./features/back_navigation.feature:4 took 152ms
   √ When I tap the "increment" button # ./features/back_navigation.feature:5 took 476ms
   √ Then I expect the "counter" to be "1" # ./features/back_navigation.feature:6 took 112ms
   √ Given I tap the label that contains the text "Open page 2" # ./features/back_navigation.feature:8 took 371ms
   √ Then I expect the text "Contents of page 2" to be present # ./features/back_navigation.feature:9 took 24ms
   √ Given I tap the back button # ./features/back_navigation.feature:11 took 379ms
   √ Then I expect the "counter" to be "1" # ./features/back_navigation.feature:12 took 29ms
PASSED: Scenario User can navigate back from page two # ./features/back_navigation.feature:3
Restarting Flutter app under test
running hook after scenario 'User can navigate back from page two'
VMServiceFlutterDriver Connecting to Flutter application at http://127.0.0.1:33783/7QZcLiOzt4E=/
Error waiting for no transient callbacks from Flutter driver:

`Failed assertion: boolean expression must not be null`

#0      VMServiceFlutterDriver.sendCommand (package:flutter_driver/src/driver/vmservice_driver.dart:351:29)
<asynchronous suspension>
#1      FlutterDriver.waitUntilNoTransientCallbacks (package:flutter_driver/src/driver/driver.dart:230:11)
#2      FlutterWorld._closeDriver (package:flutter_gherkin/src/flutter/flutter_world.dart:49:14)
#3      FlutterWorld.dispose (package:flutter_gherkin/src/flutter/flutter_world.dart:40:11)
#4      FeatureFileRunner._runScenario (package:gherkin/src/feature_file_runner.dart:276:16)
<asynchronous suspension>
#5      FeatureFileRunner._runScenarioInZone.<anonymous closure> (package:gherkin/src/feature_file_runner.dart:142:30)
#6      _rootRun (dart:async/zone.dart:1190:13)
#7      _CustomZone.run (dart:async/zone.dart:1093:19)
#8      _runZoned (dart:async/zone.dart:1630:10)
#9      runZonedGuarded (dart:async/zone.dart:1618:12)
#10     runZoned (dart:async/zone.dart:1547:12)
#11     FeatureFileRunner._runScenarioInZone (package:gherkin/src/feature_file_runner.dart:140:5)
#12     FeatureFileRunner._runFeature (package:gherkin/src/feature_file_runner.dart:74:21)
<asynchronous suspension>
#13     FeatureFileRunner.run (package:gherkin/src/feature_file_runner.dart:41:38)
#14     GherkinRunner.execute (package:gherkin/src/test_runner.dart:86:45)
<asynchronous suspension>
#15     main (file:///home/aka/try-flutter/flutter_gherkin/example/test_driver/app_test.dart:40:26)
#16     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

...
```

**Comment by comerc** [comment]
$ flutter doctor -v
Waiting for another flutter command to release the startup lock...
[✓] Flutter (Channel stable, 1.22.2, on Linux, locale ru_RU.UTF-8)
    • Flutter version 1.22.2 at /home/aka/flutter
    • Framework revision 84f3d28555 (3 недели назад), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/aka/Android/Sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.9+11-Ubuntu-0ubuntu1.18.04.1)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

! Doctor found issues in 2 categories.

**Comment by lukasgarcya** [comment]
This error is mentioned in #92

**Comment by jonsamwell** [comment]
Does this actually make the test fail or just print the error message

**Comment by jonsamwell** [comment]
Can you please see if the error is still present using this branch https://github.com/jonsamwell/flutter_gherkin/tree/close-driver-error-fix

**Comment by comerc** [comment]
> Does this actually make the test fail or just print the error message

 just print the error message :)

**Comment by comerc** [comment]
> Can you please see if the error is still present using this branch https://github.com/jonsamwell/flutter_gherkin/tree/close-driver-error-fix

its work fine for me :)

**Comment by jonsamwell** [comment]
Great, I'll get this merged in tomorrow
